"""U2Wardrobe installer: one outfit list -> script defaults, the F6 menu, and the game hooks.

    python make_wardrobe_ui.py            write Wardrobe.ui + defaults, hook the game in (idempotent)
    python make_wardrobe_ui.py --undo     take the hooks out again (backups: *.before-wardrobe)

Hooks: UI.ui and ModUI.ui include Wardrobe.Wardrobe; User.ini binds F6 to the menu and adds
U2Wardrobe.WardrobeMutator to the Mutator line; Unreal2.ini gets EditPackages=U2Wardrobe.
Then run ucc make (System\\ucc.exe make).
"""
import os
import re
import shutil
import sys

GAME = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SYSTEM = os.path.join(GAME, "System")
UI = os.path.join(GAME, "UIScripts")
MESHES = os.path.join(GAME, "Meshes")

# (menu label, Golem mesh). Dalton and human player characters only (user's choice,
# 2026-09-30). "Dalton" means the game's own: his armour on missions and off-duty
# clothes on the Atlantis, as the game picks; any other choice replaces him
# everywhere, cutscenes included.
GAME_OUTFITS = [
    ("Dalton", "GlmCharactersG.PlayerGame"),
]
# human UT2004 characters imported with tools\python\U2Golem (only the ones whose package exists are listed)
IMPORTED = [
    ("Malcolm (UT2004)", "Malcolm"),
    ("Merc (UT2004)", "MercMaleA"),
    ("Merc woman (UT2004)", "MercFemaleA"),
    ("Egyptian (UT2004)", "EgyptMaleA"),
    ("Necris (UT2004)", "NightMaleA"),
    ("Juggernaut (UT2004)", "JuggMaleA"),
]


def outfits():
    out = list(GAME_OUTFITS)
    for label, name in IMPORTED:
        if os.path.exists(os.path.join(MESHES, "Glm%sG.ugx" % name)):
            out.append((label, "Glm%sG.%s" % (name, name)))
    return out


def backup(path):
    b = path + ".before-wardrobe"
    if os.path.exists(path) and not os.path.exists(b):
        shutil.copy(path, b)


def button(key, text, action, x, y, w=170):
    return (f"[{key}]\nClass=Button\nText={text}\nAction=ConsoleCommand,{action}\nSize={w},20\n"
            f"Location={x},{y}\nFont=Engine.smallfont\nUpImage=DarkGray\nDownImage=Gray\nColor=255,255,255,192\n\n")


def write_ui(items):
    per_col, col_w, row_h = 9, 180, 24          # 3 columns, clear of the HUD bars at the bottom
    comps, parts = [], []
    for i, (label, _) in enumerate(items):
        key = "WardrobeItem%02d" % i
        comps.append(key)
        parts.append(button(key, label, "wardrobe wear " + label, (i // per_col) * col_w, 40 + (i % per_col) * row_h))
    y = 40 + per_col * row_h + 10
    for key, text, act, x in (("WardrobePrev", "< Previous", "wardrobe prev", 0),
                              ("WardrobeNext", "Next >", "wardrobe next", col_w),
                              ("WardrobeView", "Third person on/off", "wardrobe view", 2 * col_w)):
        comps.append(key)
        parts.append(button(key, text, act, x, y))
    head = f"""### U2Wardrobe: F6 menu to dress Dalton (generated by U2Wardrobe\\make_wardrobe_ui.py) ###

[Root]
Class=FixedSizeContainer
Component=CodeMonkey
Component=Wardrobe

; each .ui file registers its own CodeMonkey (U2Menus.ui, U2HUD.ui, Console.ui do the same)
[CodeMonkey]
Helper=U2$CodeMonkey
RegisterObj=CodeMonkey

[Wardrobe]
Class=MultiStateComponent
State=WardrobeNull
State=WardrobePage
Transition=HideWardrobe,1,0,0.3,WardrobePage
Transition=ShowWardrobe,0,1,0.3,WardrobePage
NextTransitionEvent=ToggleWardrobe
; like the pause menu: pausing hands the mouse to the menu (otherwise it keeps aiming and a click fires)
TriggerEvent=1,0.0,ConsoleCommand,wardrobe opened
TriggerEvent=1,0.0,CodeMonkey,Pause
TriggerEvent=0,0.0,CodeMonkey,UnPause
TriggerEvent=0,0.0,ConsoleCommand,wardrobe closed
TweenColor=true
Alignment=Left,Top
Location=40,70

[WardrobeNull]
Class=RealComponent
Location=-600,0
Color=0,0,0,0

[WardrobeMouse]
Class=MouseCursor
Image=MouseCursor

[WardrobeTitle]
Class=Label
Font=Engine.smallfont
Text=WARDROBE - dress Dalton (F6 closes)
Location=0,10
DrawOrder=1

[WardrobeClose]
Class=Label
Font=Engine.smallfont
Text=[X]
MouseClick=Event,HideWardrobe
Location={3 * col_w - 20},10
DrawOrder=1

[WardrobePage]
Class=FixedSizeContainer
Component=WardrobeMouse
Component=WardrobeTitle
Component=WardrobeClose
""" + "".join("Component=%s\n" % c for c in comps) + "\n"
    with open(os.path.join(UI, "Wardrobe.ui"), "w", newline="\r\n") as f:
        f.write(head + "".join(parts))


def write_defaults(items):
    p = os.path.join(GAME, "U2Wardrobe", "Classes", "WardrobeMutator.uc")
    s = open(p).read()
    lines = "".join('\tLabels(%d)="%s"\n\tMeshes(%d)="%s"\n' % (i, l, i, m) for i, (l, m) in enumerate(items))
    s = re.sub(r"(\t// OUTFITS-BEGIN[^\n]*\n).*?(\t// OUTFITS-END)", lambda m: m.group(1) + lines + m.group(2), s, flags=re.S)
    open(p, "w").write(s)


def write_ini(items):
    """the list is config: System/U2Wardrobe.ini overrides the script defaults, so rewrite it there too"""
    p = os.path.join(SYSTEM, "U2Wardrobe.ini")
    outfit, keep = "Dalton", []
    if os.path.exists(p):
        backup(p)
        for line in open(p, encoding="latin-1"):
            if line.startswith("Outfit="):
                outfit = line.strip().split("=", 1)[1]
            elif "=" in line and not line.startswith(("Labels=", "Meshes=")):
                keep.append(line.strip())          # other settings (bFirstPersonBody, ...)
    if outfit not in [l for l, _ in items]:
        outfit = "Dalton"
    body = ["[U2Wardrobe.WardrobeMutator]", "Outfit=" + outfit] + keep
    body += ["Labels=" + l for l, _ in items] + ["Meshes=" + m for _, m in items]
    open(p, "w", encoding="latin-1", newline="\r\n").write("\n".join(body) + "\n")


def hook(undo=False):
    for name in ("UI.ui", "ModUI.ui"):
        p = os.path.join(UI, name)
        if not os.path.exists(p):
            continue
        s = open(p).read()
        line = "Component=Wardrobe.Root\n"          # Root, so the file's own CodeMonkey gets registered
        if undo:
            s = s.replace(line, "")
        elif line not in s:
            backup(p)
            s = s.replace("Component=SummonMenu.SummonMenu\n", "Component=SummonMenu.SummonMenu\n" + line, 1)
        open(p, "w").write(s)
    p = os.path.join(SYSTEM, "User.ini")
    s = open(p).read()
    if undo:
        s = s.replace("F6=SendEvent ToggleWardrobe", "F6=").replace(",U2Wardrobe.WardrobeMutator", "")
    else:
        backup(p)
        s = re.sub(r"(?m)^F6=$", "F6=SendEvent ToggleWardrobe", s)
        if "U2Wardrobe.WardrobeMutator" not in s:
            s = re.sub(r"(?m)^(Mutator=.+)$", r"\1,U2Wardrobe.WardrobeMutator", s, count=1)
    open(p, "w").write(s)
    p = os.path.join(SYSTEM, "Unreal2.ini")
    s = open(p).read()
    if undo:
        s = s.replace("EditPackages=U2Wardrobe\n", "")
    elif "EditPackages=U2Wardrobe" not in s:
        backup(p)
        s = s.replace("EditPackages=U2TestHub\n", "EditPackages=U2TestHub\nEditPackages=U2Wardrobe\n", 1)
    open(p, "w").write(s)


if __name__ == "__main__":
    if "--undo" in sys.argv:
        hook(undo=True)
        print("hooks removed")
    else:
        items = outfits()
        write_defaults(items)
        write_ui(items)
        write_ini(items)
        hook()
        print("%d outfits: %s" % (len(items), ", ".join(l for l, _ in items)))
        print("now run: System\\ucc.exe make")
