"""Writes UIScripts/U2Gore.ui: the blood-on-screen layouts GoreManager.ScreenSplash shows.

    python make_ui.py

Three layouts per colour (ScreenBlood0..2 red, ScreenIchor0..2 green). Each is a 1024x768 container with
three splats near the left and right edges (the middle of the screen stays readable); each splat fades
from its start alpha to nothing over 3-4.5 s (AlphaAccess=Keyframe|value|seconds|...), and GoreManager
removes the layout after 4.6 s. An Image section names one material, so there is one per texture.
Seeded: every run writes the same file. Copy the result to <game>/UIScripts.
"""
import os, random

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "UIScripts")
os.makedirs(OUT, exist_ok=True)
rng = random.Random(7)
ui = ["### U2Gore: blood on the screen when something dies close to the player (generated by tools/make_ui.py) ###", ""]
for pre in ("Blood", "Ichor"):
    for i in range(4):
        t = "%sSplat%d" % (pre, i)
        ui += ["[Gore%s]" % t, "Class=Image", "Material=U2Gore.%s" % t, "Image=GoreImg%s,0,0,128,128" % t, ""]
for pre in ("Blood", "Ichor"):
    for lay in range(3):
        name = "Screen%s%d" % (pre, lay)
        ui += ["[%s]" % name, "Class=FixedSizeContainer", "Alignment=HardCenter,HardCenter", "Size=1024,768"]
        ui += ["Component=Gore%sSplat%d" % (pre, i) for i in range(4)]
        ui += ["Component=%s_%d" % (name, k) for k in range(3)]
        ui.append("")
        for k in range(3):
            size = rng.randint(230, 380)
            side = rng.choice((0, 1)) if k else lay % 2
            x = rng.randint(-40, 170) if side == 0 else rng.randint(1024 - 130 - size, 1024 - size + 40)
            y = rng.randint(-30, 768 - size + 30)
            life = 3.0 + rng.random() * 1.5
            ui += ["[%s_%d]" % (name, k), "Class=ImageComponent", "Image=GoreImg%sSplat%d" % (pre, rng.randrange(4)),
                   "Location=%d,%d" % (x, y), "Size=%d,%d" % (size, size), "Style=Alpha",
                   "AlphaAccess=Keyframe|%d|0|0|%.1f|0|0|0|60" % (rng.randint(170, 230), life), ""]
open(os.path.join(OUT, "U2Gore.ui"), "w", newline="\r\n").write("\n".join(ui))
print(os.path.join(OUT, "U2Gore.ui"))
