//=============================================================================
// SevenScript - GENERATED by build_voices.py from story.py. Do not edit.
// Every line of The Seven: speaker, subtitle, sound, length; the cue it
// belongs to (0 = the episode's intro, 1+ = mid-mission cues) and, for a
// cue's first line, how many seconds after the intro it starts.
//=============================================================================
class SevenScript extends Info;

#exec AUDIO IMPORT FILE=Sounds\E1C0_00.wav NAME=E1C0_00 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E1C0_02.wav NAME=E1C0_02 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E1C0_03.wav NAME=E1C0_03 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E1C0_05.wav NAME=E1C0_05 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E1C1_00.wav NAME=E1C1_00 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E1C1_01.wav NAME=E1C1_01 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E2C0_00.wav NAME=E2C0_00 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E2C0_01.wav NAME=E2C0_01 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E2C0_03.wav NAME=E2C0_03 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E2C0_04.wav NAME=E2C0_04 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E2C0_06.wav NAME=E2C0_06 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E2C0_07.wav NAME=E2C0_07 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E2C0_08.wav NAME=E2C0_08 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E2C0_09.wav NAME=E2C0_09 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E2C0_10.wav NAME=E2C0_10 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E2C0_12.wav NAME=E2C0_12 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E2C0_13.wav NAME=E2C0_13 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\Static20.wav NAME=Static20 GROUP=Radio
#exec AUDIO IMPORT FILE=Sounds\E2C0_15.wav NAME=E2C0_15 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E2C0_17.wav NAME=E2C0_17 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E2C0_18.wav NAME=E2C0_18 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E2C0_19.wav NAME=E2C0_19 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E2C1_00.wav NAME=E2C1_00 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E3C0_00.wav NAME=E3C0_00 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E3C0_01.wav NAME=E3C0_01 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E3C0_02.wav NAME=E3C0_02 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E3C0_04.wav NAME=E3C0_04 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E3C0_06.wav NAME=E3C0_06 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\Static15.wav NAME=Static15 GROUP=Radio
#exec AUDIO IMPORT FILE=Sounds\E3C0_08.wav NAME=E3C0_08 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E3C0_09.wav NAME=E3C0_09 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E3C0_10.wav NAME=E3C0_10 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E3C0_11.wav NAME=E3C0_11 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E4C0_00.wav NAME=E4C0_00 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E4C0_01.wav NAME=E4C0_01 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E4C0_02.wav NAME=E4C0_02 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E4C0_03.wav NAME=E4C0_03 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E4C0_04.wav NAME=E4C0_04 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E4C0_05.wav NAME=E4C0_05 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E4C0_06.wav NAME=E4C0_06 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E4C0_08.wav NAME=E4C0_08 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E4C0_10.wav NAME=E4C0_10 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E4C0_12.wav NAME=E4C0_12 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E4C0_13.wav NAME=E4C0_13 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E4C0_14.wav NAME=E4C0_14 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E4C0_15.wav NAME=E4C0_15 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E4C0_16.wav NAME=E4C0_16 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E5C0_00.wav NAME=E5C0_00 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E5C0_01.wav NAME=E5C0_01 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E5C0_02.wav NAME=E5C0_02 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\Static12.wav NAME=Static12 GROUP=Radio
#exec AUDIO IMPORT FILE=Sounds\E5C0_04.wav NAME=E5C0_04 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E5C0_05.wav NAME=E5C0_05 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E5C0_07.wav NAME=E5C0_07 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E5C0_09.wav NAME=E5C0_09 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E5C0_10.wav NAME=E5C0_10 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E5C0_11.wav NAME=E5C0_11 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E5C1_00.wav NAME=E5C1_00 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\Static10.wav NAME=Static10 GROUP=Radio
#exec AUDIO IMPORT FILE=Sounds\E5C1_02.wav NAME=E5C1_02 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E5C1_04.wav NAME=E5C1_04 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\Static06.wav NAME=Static06 GROUP=Radio
#exec AUDIO IMPORT FILE=Sounds\E6C0_00.wav NAME=E6C0_00 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E6C0_01.wav NAME=E6C0_01 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E6C0_02.wav NAME=E6C0_02 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E6C0_03.wav NAME=E6C0_03 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E6C0_04.wav NAME=E6C0_04 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E6C0_05.wav NAME=E6C0_05 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E6C0_06.wav NAME=E6C0_06 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E6C0_08.wav NAME=E6C0_08 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E6C0_10.wav NAME=E6C0_10 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E6C0_11.wav NAME=E6C0_11 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E6C0_12.wav NAME=E6C0_12 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E6C0_14.wav NAME=E6C0_14 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E6C0_15.wav NAME=E6C0_15 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E7C0_00.wav NAME=E7C0_00 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\Static05.wav NAME=Static05 GROUP=Radio
#exec AUDIO IMPORT FILE=Sounds\E7C0_03.wav NAME=E7C0_03 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E7C0_05.wav NAME=E7C0_05 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E7C0_06.wav NAME=E7C0_06 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E7C0_08.wav NAME=E7C0_08 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E8C0_00.wav NAME=E8C0_00 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E8C0_01.wav NAME=E8C0_01 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E8C0_03.wav NAME=E8C0_03 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E8C0_04.wav NAME=E8C0_04 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E8C0_05.wav NAME=E8C0_05 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E8C0_07.wav NAME=E8C0_07 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E8C0_08.wav NAME=E8C0_08 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E8C0_09.wav NAME=E8C0_09 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E8C0_11.wav NAME=E8C0_11 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E8C0_13.wav NAME=E8C0_13 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E8C0_15.wav NAME=E8C0_15 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\Static04.wav NAME=Static04 GROUP=Radio
#exec AUDIO IMPORT FILE=Sounds\E8C0_18.wav NAME=E8C0_18 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E8C0_20.wav NAME=E8C0_20 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E9C0_01.wav NAME=E9C0_01 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E9C0_03.wav NAME=E9C0_03 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E9C0_05.wav NAME=E9C0_05 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E9C0_06.wav NAME=E9C0_06 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E9C0_08.wav NAME=E9C0_08 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E10C0_01.wav NAME=E10C0_01 GROUP=VO
#exec AUDIO IMPORT FILE=Sounds\E10C0_03.wav NAME=E10C0_03 GROUP=VO

struct SevenLine
{
	var int Ep, Cue;
	var float CueDelay;
	var string Speaker, Text;
	var Sound Snd;
	var float Dur;
};

struct EpisodeMap
{
	var int Ep;
	var string Map;
};

var array<SevenLine> Lines;
var array<EpisodeMap> EpisodeMaps;
var array<string> MutedNodes;      // original dialogue nodes silenced (see story.MUTE)

defaultproperties
{
	Lines(0)=(Ep=1,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Marshal's log. Sanctuary went quiet three days ago. Quiet is an answer.",Snd=Sound'E1C0_00',Dur=6.08)
	Lines(1)=(Ep=1,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=0.80)
	Lines(2)=(Ep=1,Cue=0,CueDelay=0.0,Speaker="NE'BAN",Text="Landing zone is clear, Marshal. Nothing moves.",Snd=Sound'E1C0_02',Dur=3.99)
	Lines(3)=(Ep=1,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="Three hundred people. Nothing moves.",Snd=Sound'E1C0_03',Dur=2.42)
	Lines(4)=(Ep=1,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.20)
	Lines(5)=(Ep=1,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Keep the engines warm.",Snd=Sound'E1C0_05',Dur=2.05)
	Lines(6)=(Ep=1,Cue=1,CueDelay=50.0,Speaker="AIDA",Text="Izarians. Skaarj slave troops.",Snd=Sound'E1C1_00',Dur=2.47)
	Lines(7)=(Ep=1,Cue=1,CueDelay=50.0,Speaker="DALTON",Text="Then there's a Skaarj holding the leash.",Snd=Sound'E1C1_01',Dur=2.87)
	Lines(8)=(Ep=1,Cue=1,CueDelay=50.0,Speaker="",Text="",Snd=None,Dur=1.00)
	Lines(9)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Marshal's log. We found it under the colony. A marine was holding it. He'd held it a long time.",Snd=Sound'E2C0_00',Dur=7.32)
	Lines(10)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="It looks alien. And old. Older than anything I've seen.",Snd=Sound'E2C0_01',Dur=4.69)
	Lines(11)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=0.80)
	Lines(12)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="I decrypted a Skaarj intercept. They want that thing, Dalton. Badly.",Snd=Sound'E2C0_03',Dur=4.34)
	Lines(13)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Then they'll have to come and get it.",Snd=Sound'E2C0_04',Dur=2.23)
	Lines(14)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.20)
	Lines(15)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="Marshal Dalton. Hawkins, liaison to Command. Command is grateful.",Snd=Sound'E2C0_06',Dur=5.47)
	Lines(16)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="There are six more. I will send the coordinates. Rest first. Please.",Snd=Sound'E2C0_07',Dur=5.61)
	Lines(17)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="He said please.",Snd=Sound'E2C0_08',Dur=1.45)
	Lines(18)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="He did.",Snd=Sound'E2C0_09',Dur=1.05)
	Lines(19)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="Nobody says please to us.",Snd=Sound'E2C0_10',Dur=2.05)
	Lines(20)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.50)
	Lines(21)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="NE'BAN",Text="Mayday. Mayday. We are hit. We are going down.",Snd=Sound'E2C0_12',Dur=4.21)
	Lines(22)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="ISAAK",Text="She'll hold. She'll hold.",Snd=Sound'E2C0_13',Dur=1.83)
	Lines(23)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=Sound'Static20',Dur=2.00)
	Lines(24)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="Dalton.",Snd=Sound'E2C0_15',Dur=0.94)
	Lines(25)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.00)
	Lines(26)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="Dalton.",Snd=Sound'E2C0_17',Dur=0.97)
	Lines(27)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Here.",Snd=Sound'E2C0_18',Dur=1.06)
	Lines(28)=(Ep=2,Cue=0,CueDelay=0.0,Speaker="ISAAK",Text="She held. Mostly. Give me an hour. Keep them off her.",Snd=Sound'E2C0_19',Dur=4.38)
	Lines(29)=(Ep=2,Cue=1,CueDelay=75.0,Speaker="AIDA",Text="Nobody knew our route. Nobody but Command.",Snd=Sound'E2C1_00',Dur=2.91)
	Lines(30)=(Ep=2,Cue=1,CueDelay=75.0,Speaker="",Text="",Snd=None,Dur=2.00)
	Lines(31)=(Ep=3,Cue=0,CueDelay=0.0,Speaker="ISAAK",Text="Engines.",Snd=Sound'E3C0_00',Dur=1.24)
	Lines(32)=(Ep=3,Cue=0,CueDelay=0.0,Speaker="NE'BAN",Text="Lifting.",Snd=Sound'E3C0_01',Dur=1.22)
	Lines(33)=(Ep=3,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Marshal's log. We fell. We got up. One in the hold. Six to go.",Snd=Sound'E3C0_02',Dur=6.56)
	Lines(34)=(Ep=3,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.50)
	Lines(35)=(Ep=3,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Marshal's log. Hell is cold. The Izarians took the second one. Hawkins says Drexler asked for me.",Snd=Sound'E3C0_04',Dur=8.34)
	Lines(36)=(Ep=3,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.00)
	Lines(37)=(Ep=3,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="Drexler asked about you. He remembers Kalydon, Marshal. He says the Colonel's chair is still empty.",Snd=Sound'E3C0_06',Dur=7.48)
	Lines(38)=(Ep=3,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=Sound'Static15',Dur=1.50)
	Lines(39)=(Ep=3,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="Take your time. The Izarians aren't going anywhere.",Snd=Sound'E3C0_08',Dur=3.55)
	Lines(40)=(Ep=3,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="He knew about Kalydon.",Snd=Sound'E3C0_09',Dur=1.72)
	Lines(41)=(Ep=3,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Everyone knows about Kalydon.",Snd=Sound'E3C0_10',Dur=2.64)
	Lines(42)=(Ep=3,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="Nobody says it that kindly.",Snd=Sound'E3C0_11',Dur=1.94)
	Lines(43)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="Tell me what the job is.",Snd=Sound'E4C0_00',Dur=1.72)
	Lines(44)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Collect. Deliver. Get paid.",Snd=Sound'E4C0_01',Dur=2.88)
	Lines(45)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="Tell me who pays.",Snd=Sound'E4C0_02',Dur=1.39)
	Lines(46)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Command.",Snd=Sound'E4C0_03',Dur=1.12)
	Lines(47)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="You've never met Command. You've met a voice with no static on it.",Snd=Sound'E4C0_04',Dur=3.56)
	Lines(48)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="I wore their stripes for twenty years. I know how they talk.",Snd=Sound'E4C0_05',Dur=4.22)
	Lines(49)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="Then you know they never say please.",Snd=Sound'E4C0_06',Dur=2.34)
	Lines(50)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.50)
	Lines(51)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Two in the hold. Five to go.",Snd=Sound'E4C0_08',Dur=2.78)
	Lines(52)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.50)
	Lines(53)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Marshal's log. Acheron is alive. The ground breathes. Ne'Ban won't look at it.",Snd=Sound'E4C0_10',Dur=6.82)
	Lines(54)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=0.80)
	Lines(55)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="NE'BAN",Text="On my world we have a word for places like this. The listening ground.",Snd=Sound'E4C0_12',Dur=5.26)
	Lines(56)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="What's it listening for?",Snd=Sound'E4C0_13',Dur=1.58)
	Lines(57)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="NE'BAN",Text="What you want. Be careful what you want here, Marshal.",Snd=Sound'E4C0_14',Dur=3.53)
	Lines(58)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="I want the artifact.",Snd=Sound'E4C0_15',Dur=1.74)
	Lines(59)=(Ep=4,Cue=0,CueDelay=0.0,Speaker="NE'BAN",Text="That is what you say.",Snd=Sound'E4C0_16',Dur=1.68)
	Lines(60)=(Ep=5,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="I pulled the traffic logs. Every order came down one channel.",Snd=Sound'E5C0_00',Dur=3.88)
	Lines(61)=(Ep=5,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Command's channel.",Snd=Sound'E5C0_01',Dur=1.58)
	Lines(62)=(Ep=5,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="Hawkins's channel. There's no one behind it. It's a room with one man in it.",Snd=Sound'E5C0_02',Dur=4.35)
	Lines(63)=(Ep=5,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=Sound'Static12',Dur=1.20)
	Lines(64)=(Ep=5,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Three in the hold.",Snd=Sound'E5C0_04',Dur=1.74)
	Lines(65)=(Ep=5,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="You can't count your way out of this.",Snd=Sound'E5C0_05',Dur=1.94)
	Lines(66)=(Ep=5,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.50)
	Lines(67)=(Ep=5,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Marshal's log. A research station. A doctor with two of them, and a lot to say.",Snd=Sound'E5C0_07',Dur=7.35)
	Lines(68)=(Ep=5,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=0.80)
	Lines(69)=(Ep=5,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="Doctor Meyer is brilliant, and very tired. Collect the artifacts. Don't trouble her with questions.",Snd=Sound'E5C0_09',Dur=7.63)
	Lines(70)=(Ep=5,Cue=0,CueDelay=0.0,Speaker="NE'BAN",Text="Why would questions trouble her?",Snd=Sound'E5C0_10',Dur=2.44)
	Lines(71)=(Ep=5,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="Everything troubles her. It's why she's brilliant.",Snd=Sound'E5C0_11',Dur=3.64)
	Lines(72)=(Ep=5,Cue=1,CueDelay=120.0,Speaker="MEYER",Text="Day forty. They are not tools. Not weapons. A key.",Snd=Sound'E5C1_00',Dur=4.89)
	Lines(73)=(Ep=5,Cue=1,CueDelay=120.0,Speaker="",Text="",Snd=Sound'Static10',Dur=1.00)
	Lines(74)=(Ep=5,Cue=1,CueDelay=120.0,Speaker="MEYER",Text="Something asleep in the blood of...",Snd=Sound'E5C1_02',Dur=2.22)
	Lines(75)=(Ep=5,Cue=1,CueDelay=120.0,Speaker="",Text="",Snd=Sound'Static10',Dur=1.00)
	Lines(76)=(Ep=5,Cue=1,CueDelay=120.0,Speaker="MEYER",Text="Whoever is collecting them knows. Don't give them all to...",Snd=Sound'E5C1_04',Dur=4.30)
	Lines(77)=(Ep=5,Cue=1,CueDelay=120.0,Speaker="",Text="",Snd=Sound'Static06',Dur=0.60)
	Lines(78)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="NE'BAN",Text="Five in the hold. You feel them, Isaak. At night.",Snd=Sound'E6C0_00',Dur=4.07)
	Lines(79)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="ISAAK",Text="I feel the reactor. That's what I feel.",Snd=Sound'E6C0_01',Dur=3.25)
	Lines(80)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="NE'BAN",Text="They are waiting. The thing that sleeps does not dream of us.",Snd=Sound'E6C0_02',Dur=4.12)
	Lines(81)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="ISAAK",Text="I don't need to know what they are. I need to know where they go.",Snd=Sound'E6C0_03',Dur=3.69)
	Lines(82)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="NE'BAN",Text="And if where they go is the end of us?",Snd=Sound'E6C0_04',Dur=2.51)
	Lines(83)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="ISAAK",Text="Then someone above me decided. That's what above means.",Snd=Sound'E6C0_05',Dur=3.59)
	Lines(84)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="Why don't we just destroy the ones we've already got?",Snd=Sound'E6C0_06',Dur=3.04)
	Lines(85)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=2.50)
	Lines(86)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Marshal's log. Six in the hold. Hawkins wants Ne'Ban off my ship. He asked nicely.",Snd=Sound'E6C0_08',Dur=7.08)
	Lines(87)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=0.80)
	Lines(88)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="A small thing, Marshal. Your pilot. Command would feel better with a human at the controls.",Snd=Sound'E6C0_10',Dur=6.69)
	Lines(89)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Command can come and fly her.",Snd=Sound'E6C0_11',Dur=2.76)
	Lines(90)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="Of course. Forget I asked. Command is grateful.",Snd=Sound'E6C0_12',Dur=4.33)
	Lines(91)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.00)
	Lines(92)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="NE'BAN",Text="Thank you, Marshal.",Snd=Sound'E6C0_14',Dur=1.63)
	Lines(93)=(Ep=6,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Fly.",Snd=Sound'E6C0_15',Dur=1.12)
	Lines(94)=(Ep=7,Cue=0,CueDelay=0.0,Speaker="ISAAK",Text="Understood. I'll keep an eye on them.",Snd=Sound'E7C0_00',Dur=2.53)
	Lines(95)=(Ep=7,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=Sound'Static05',Dur=0.50)
	Lines(96)=(Ep=7,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.50)
	Lines(97)=(Ep=7,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Marshal's log. The last one. After this, the chair. I keep saying it. It gets quieter every time.",Snd=Sound'E7C0_03',Dur=8.04)
	Lines(98)=(Ep=7,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=0.80)
	Lines(99)=(Ep=7,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="Isaak's been in the hold two days.",Snd=Sound'E7C0_05',Dur=2.18)
	Lines(100)=(Ep=7,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Isaak. Report.",Snd=Sound'E7C0_06',Dur=2.02)
	Lines(101)=(Ep=7,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=Sound'Static15',Dur=1.50)
	Lines(102)=(Ep=7,Cue=0,CueDelay=0.0,Speaker="NE'BAN",Text="He is there. He is listening. He does not answer.",Snd=Sound'E7C0_08',Dur=3.99)
	Lines(103)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="Seven. Remarkable. Command is grateful.",Snd=Sound'E8C0_00',Dur=3.29)
	Lines(104)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="One formality left. Command likes to be asked. Say you want it back, Marshal. The rank. Just say it.",Snd=Sound'E8C0_01',Dur=8.00)
	Lines(105)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=3.00)
	Lines(106)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Bring them to Avalon.",Snd=Sound'E8C0_03',Dur=2.30)
	Lines(107)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="That isn't what I asked.",Snd=Sound'E8C0_04',Dur=2.15)
	Lines(108)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="It's what you're getting.",Snd=Sound'E8C0_05',Dur=1.67)
	Lines(109)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.00)
	Lines(110)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="Avalon, then.",Snd=Sound'E8C0_07',Dur=1.54)
	Lines(111)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="AIDA",Text="You could have said it.",Snd=Sound'E8C0_08',Dur=1.30)
	Lines(112)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="No. I couldn't.",Snd=Sound'E8C0_09',Dur=2.00)
	Lines(113)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=2.00)
	Lines(114)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="ISAAK (log)",Text="Engineer's log. She'll hold. I told them she'd hold.",Snd=Sound'E8C0_11',Dur=4.09)
	Lines(115)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=Sound'Static10',Dur=1.00)
	Lines(116)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="ISAAK (log)",Text="She wouldn't give me the artifacts. It was my duty.",Snd=Sound'E8C0_13',Dur=4.34)
	Lines(117)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=Sound'Static10',Dur=1.00)
	Lines(118)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="ISAAK (log)",Text="She'll ho...",Snd=Sound'E8C0_15',Dur=0.70)
	Lines(119)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=Sound'Static04',Dur=0.40)
	Lines(120)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.50)
	Lines(121)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Atlantis. Aida. Ne'Ban.",Snd=Sound'E8C0_18',Dur=3.01)
	Lines(122)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=Sound'Static15',Dur=1.50)
	Lines(123)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Isaak.",Snd=Sound'E8C0_20',Dur=1.26)
	Lines(124)=(Ep=8,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=Sound'Static20',Dur=2.00)
	Lines(125)=(Ep=9,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.50)
	Lines(126)=(Ep=9,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="Thank you, Marshal. Truly. Command is grateful.",Snd=Sound'E9C0_01',Dur=4.04)
	Lines(127)=(Ep=9,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=2.00)
	Lines(128)=(Ep=9,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Marshal's log. Seven in the hold. None to go. Nobody left to read this.",Snd=Sound'E9C0_03',Dur=6.44)
	Lines(129)=(Ep=9,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.00)
	Lines(130)=(Ep=9,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="It's all right, Marshal. You did everything we asked.",Snd=Sound'E9C0_05',Dur=4.20)
	Lines(131)=(Ep=9,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="Tell me. What did you want? At the start. What did you really want?",Snd=Sound'E9C0_06',Dur=4.84)
	Lines(132)=(Ep=9,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=4.00)
	Lines(133)=(Ep=9,Cue=0,CueDelay=0.0,Speaker="HAWKINS",Text="Most men know.",Snd=Sound'E9C0_08',Dur=1.64)
	Lines(134)=(Ep=10,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=2.00)
	Lines(135)=(Ep=10,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Marshal's log.",Snd=Sound'E10C0_01',Dur=1.73)
	Lines(136)=(Ep=10,Cue=0,CueDelay=0.0,Speaker="",Text="",Snd=None,Dur=1.50)
	Lines(137)=(Ep=10,Cue=0,CueDelay=0.0,Speaker="DALTON",Text="Nothing to report.",Snd=Sound'E10C0_03',Dur=1.67)
	EpisodeMaps(0)=(Ep=1,Map="M08A1")
	EpisodeMaps(1)=(Ep=2,Map="MM_MARSH")
	EpisodeMaps(2)=(Ep=3,Map="M01A")
	EpisodeMaps(3)=(Ep=4,Map="M06_ACHERON")
	EpisodeMaps(4)=(Ep=5,Map="M09A")
	EpisodeMaps(5)=(Ep=6,Map="M03A1")
	EpisodeMaps(6)=(Ep=7,Map="M03B1")
	EpisodeMaps(7)=(Ep=8,Map="M10_AVALON")
	EpisodeMaps(8)=(Ep=9,Map="M12")
	EpisodeMaps(9)=(Ep=10,Map="CS_OUTRO")
	MutedNodes(0)="Sanctuary_15G_002"
	MutedNodes(1)="Sanctuary_15G_003"
	MutedNodes(2)="Sanctuary_15G_004"
	MutedNodes(3)="Sanctuary_15G_005"
	MutedNodes(4)="Sanctuary_15G_006a"
	MutedNodes(5)="Sanctuary_15G_006b"
	MutedNodes(6)="Sanctuary_15G_006c"
	MutedNodes(7)="Sanctuary_15G_007"
	MutedNodes(8)="Sanctuary_15G_008"
	MutedNodes(9)="Sanctuary_20_002"
	MutedNodes(10)="Sanctuary_16G_002"
	MutedNodes(11)="Sanctuary_16G_003"
	MutedNodes(12)="Sanctuary_16bG_002"
	MutedNodes(13)="Sanctuary_16bG_003"
	MutedNodes(14)="Sanctuary_16bG_003b"
	MutedNodes(15)="Sanctuary_16bG_004"
	MutedNodes(16)="Sanctuary_16bG_004b"
	MutedNodes(17)="Sanctuary_16bG_005"
	MutedNodes(18)="Sanctuary_17G_002"
	MutedNodes(19)="Sanctuary_17G_002b"
	MutedNodes(20)="Sanctuary_17bG_002"
	MutedNodes(21)="Sanctuary_18G_002"
	MutedNodes(22)="Sanctuary_19G_002"
	MutedNodes(23)="Sanctuary_20G_002"
	MutedNodes(24)="Sanctuary_21G_002"
	MutedNodes(25)="Sanctuary_21G_004"
	MutedNodes(26)="Sanctuary_21G_007"
	MutedNodes(27)="Sanctuary_21G_007b"
	MutedNodes(28)="Sanctuary_22G_002"
	MutedNodes(29)="Sanctuary_22G_003"
	MutedNodes(30)="Sanctuary_22G_004"
	MutedNodes(31)="Sanctuary_23G_002"
	MutedNodes(32)="Sanctuary_24G_002"
	MutedNodes(33)="Sanctuary_24G_003"
	MutedNodes(34)="Sanctuary_25G_002"
	MutedNodes(35)="Sanctuary_25G_003"
	MutedNodes(36)="Sanctuary_25G_004"
}
