//=============================================================================
// SevenStory - Unreal II retold as "The Seven": nine combat episodes with a
// new, voiced story arc. The maps are untouched.
//
// Level flow (bSevenFlow): like U2CombatOnly - New Game starts at Sanctuary,
//   the tutorial, the Atlantis hub and the dropship maps are skipped - and the
//   cut: Severnaya, Kalydon and Sulferon are dropped, so Acheron leads
//   straight to Janus. Episodes:
//     1 Sanctuary  2 Marsh  3 Hell  4 Acheron  5 Janus  6 Na Koja Abad
//     7 Drakk hive  8 Avalon  9 Dorian Gray  (+ an epilogue line on the outro)
// Story (bStory): when the player first gets control on an episode's first
//   map, the radio plays the previous episode's tag, the captain's log and
//   the cold open, with subtitles; some episodes add timed mid-mission lines.
//   Every line is in SevenScript (generated by build_voices.py from story.py).
//   An intro plays once: dying and reloading the same episode doesn't repeat it.
//
// U2CombatOnly is switched off while this runs (same job, different order).
// Add with ?Mutator=U2Seven.SevenStory or in User.ini's [DefaultPlayer]
// Mutator=. Settings: [U2Seven.SevenStory] in User.ini.
//=============================================================================
class SevenStory extends Mutator
	config(User);

var() config bool bSevenFlow;
var() config bool bSkipTutorial;
var() config bool bStory;
var() config bool bShortSanctuary; // play only Sanctuary's first map
var() config int LastIntroEp;      // the last episode whose intro played

// flow
var string LastSeenURL;
var bool bJumped;

// story
var int Episode;                   // this map's episode (0 = none)
var bool bIntroWanted;
var float ControlTime;             // seconds the player has been in control
var float StoryStart;              // Level.TimeSeconds when the intro began (0 = not yet)
var array<int> Queue;              // SevenScript line indices still to play
var float NextLineTime;
var array<int> PendingCues;        // mid-mission cue numbers not yet played
var SevenRadio Radio;              // where the lines play from
var int MuteTries;                 // silencing original dialogue: a few tries while the level starts
var name NodeName;                 // scratch: a MutedNodes string as a name

event PostBeginPlay()
{
	local string Dest;

	Super.PostBeginPlay();
	SaveConfig();
	DisableCombatOnly();

	// Atlantis freezes every mod's Tick, so decide at level start
	if (bSevenFlow && AtlantisGameInfo(Level.Game) != None)
	{
		Dest = Redirect(Level.GetLocalURL());
		if (Dest != "")
		{
			bJumped = true;
			Log("U2Seven: Atlantis after mission "$AtlantisGameInfo(Level.Game).LastMissionCompleted$", going to "$Dest);
			Level.ServerTravel(Dest, false);
			return;
		}
	}

	Episode = EpisodeFor(MapOf(Level.GetLocalURL()));
	// Sanctuary's opening is redirected: quiet colony, held first wave
	if (bStory && Caps(MapOf(Level.GetLocalURL())) == "M08A1")
		Spawn(class'SevenSanctuary');
	if (Left(Caps(MapOf(Level.GetLocalURL())), 7) == "PRAIRIE")
		Spawn(class'SevenPrairie');
	bIntroWanted = bStory && Episode > 0 && Episode != LastIntroEp;
	if (bIntroWanted)
		Log("U2Seven: episode "$Episode$" - intro queued");
	else if (Episode > 0)
		Log("U2Seven: episode "$Episode$" - intro already heard");
}

// U2CombatOnly does the same skipping with the original order; take it out
function DisableCombatOnly()
{
	local Mutator M, Prev;

	for (M = Level.Game.BaseMutator; M != None; M = M.NextMutator)
	{
		if (M != Self && string(M.Class.Name) ~= "CombatOnly")
		{
			if (Prev != None)
				Prev.NextMutator = M.NextMutator;
			M.Disable('Tick');
			M.Destroy();
			Log("U2Seven: U2CombatOnly switched off (U2Seven runs the level flow)");
			return;
		}
		Prev = M;
	}
}

// --- level flow ---------------------------------------------------------------

static function string MapOf(string URL)
{
	local int i;
	i = InStr(URL, "?");
	if (i >= 0)
		URL = Left(URL, i);
	i = InStr(URL, ".");
	if (i >= 0)
		URL = Left(URL, i);
	return Caps(URL);
}

static function int IntOption(string URL, string Key)
{
	local int i;
	i = InStr(Caps(URL), Caps(Key)$"=");
	if (i < 0)
		return -1;
	return int(Mid(URL, i + Len(Key) + 1));
}

function string Redirect(string URL)
{
	local string M;

	if (!bSevenFlow)
		return "";
	M = MapOf(URL);
	if (bSkipTutorial)
		switch (M)
		{
		case "CS_TITLES":
		case "TUTA":
		case "TUTB":
		case "PD_AVALON":
			// a new game: every intro plays again
			if (LastIntroEp != 0)
			{
				LastIntroEp = 0;
				SaveConfig();
			}
			return "M08A1";
		}
	switch (M)
	{
	case "PA_SANCTUARY": return "M08A1";
	case "PA_HELL":      return "M01a";
	case "PA_ACHERON":   return "M06_Acheron";
	case "PA_JANUS":     return "M09a";
	case "PA_AVALONB":   return "M10_Avalon";
	case "PD_SANCTUARY": return "MM_Marsh";
	case "PD_HELL":      return AfterAtlantis(2);
	case "PD_ACHERON":   return AfterAtlantis(8);
	case "PD_SULFERON":  return AfterAtlantis(5);
	case "PD_NAKOJA":    return AfterAtlantis(9);
	// Sanctuary: only its first map is played (the arrival and the first
	// fights); the rest of the mission is cut
	case "M08A2":
	case "M08B":
		if (bShortSanctuary)
			return "MM_Marsh";
		break;
	// the Seven cut: these missions are skipped
	case "MM_WATERFRONT":
	case "M06_OBOLUS":
	case "MM_SULFERON_ASSAULT":
	case "MM_SULFERON_DEFEND":
		return "M09a";
	case "ATLANTIS":
		if (IntOption(URL, "MissionCompleted") < 0 && AtlantisGameInfo(Level.Game) != None)
			return AfterAtlantis(AtlantisGameInfo(Level.Game).LastMissionCompleted);
		return AfterAtlantis(IntOption(URL, "MissionCompleted"));
	}
	return "";
}

// Atlantis?MissionCompleted=N -> the next episode
function string AfterAtlantis(int N)
{
	switch (N)
	{
	case 0:  return "M08A1";        // Sanctuary
	case 1:  return "M01a";         // Hell
	case 2:  return "M06_Acheron";  // Acheron
	case 8:                         // after Acheron: Severnaya, Kalydon and
	case 4:                         // Sulferon are cut, on to Janus
	case 6:
	case 5:  return "M09a";         // Janus
	case 7:  return "M03a1";        // Na Koja Abad
	case 9:  return "M03b1";        // the Drakk hive
	case 10: return "M10_Avalon";   // Avalon
	}
	return "";
}

function TickFlow()
{
	local string Dest;
	local Controller C;

	if (Level.NextURL != "" && Level.NextURL != LastSeenURL)
	{
		LastSeenURL = Level.NextURL;
		Dest = Redirect(Level.NextURL);
		if (Dest != "" && MapOf(Dest) != MapOf(Level.NextURL))
		{
			Log("U2Seven: "$Level.NextURL$" -> "$Dest);
			Level.NextURL = Dest;
			LastSeenURL = Dest;
		}
		return;
	}
	if (bJumped || Level.NextURL != "")
		return;
	Dest = Redirect(Level.GetLocalURL());
	if (Dest == "")
		return;
	for (C = Level.ControllerList; C != None; C = C.NextController)
		if (PlayerController(C) != None)
		{
			bJumped = true;
			Log("U2Seven: on "$Level.GetLocalURL()$", going to "$Dest);
			Level.ServerTravel(Dest, false);
			return;
		}
}

// --- the story ------------------------------------------------------------------

static function int EpisodeFor(string MapName)
{
	local int i;
	for (i = 0; i < class'SevenScript'.default.EpisodeMaps.Length; i++)
		if (class'SevenScript'.default.EpisodeMaps[i].Map ~= MapName)
			return class'SevenScript'.default.EpisodeMaps[i].Ep;
	return 0;
}

function PlayerController ThePlayer()
{
	local Controller C;
	for (C = Level.ControllerList; C != None; C = C.NextController)
		if (PlayerController(C) != None)
			return PlayerController(C);
	return None;
}

// queue every line of this episode's cue N
function QueueCue(int Cue)
{
	local int i;
	for (i = 0; i < class'SevenScript'.default.Lines.Length; i++)
		if (class'SevenScript'.default.Lines[i].Ep == Episode && class'SevenScript'.default.Lines[i].Cue == Cue)
			Queue[Queue.Length] = i;
}

function StartIntro()
{
	local int i, Cue;

	StoryStart = Level.TimeSeconds;
	LastIntroEp = Episode;
	SaveConfig();
	QueueCue(0);
	for (i = 0; i < class'SevenScript'.default.Lines.Length; i++)
	{
		Cue = class'SevenScript'.default.Lines[i].Cue;
		if (class'SevenScript'.default.Lines[i].Ep == Episode && Cue > 0
			&& (PendingCues.Length == 0 || PendingCues[PendingCues.Length - 1] != Cue))
			PendingCues[PendingCues.Length] = Cue;
	}
	NextLineTime = Level.TimeSeconds;
	Log("U2Seven: episode "$Episode$" intro, "$Queue.Length$" lines, "$PendingCues.Length$" later cues");
}

// the first line of cue N says when it starts (seconds after the intro began)
function float CueStart(int Cue)
{
	local int i;
	for (i = 0; i < class'SevenScript'.default.Lines.Length; i++)
		if (class'SevenScript'.default.Lines[i].Ep == Episode && class'SevenScript'.default.Lines[i].Cue == Cue)
			return class'SevenScript'.default.Lines[i].CueDelay;
	return 0;
}

// play one line by episode and cue (the board's Aida lines are episode 99)
function Say(int Ep, int Cue)
{
	local int i;
	local PlayerController PC;

	PC = ThePlayer();
	if (PC == None)
		return;
	for (i = 0; i < class'SevenScript'.default.Lines.Length; i++)
		if (class'SevenScript'.default.Lines[i].Ep == Ep && class'SevenScript'.default.Lines[i].Cue == Cue)
		{
			PlayLine(PC, i);
			return;
		}
}

// the mission board's number keys, bound through the console: "seven 1" etc.
function Choose(int N)
{
	local SevenBoard B;
	foreach DynamicActors(class'SevenBoard', B)
		B.Choose(N);
}

function PlayLine(PlayerController PC, int i)
{
	local Sound S;
	local string Who, What;
	local float Dur;
	local DialogEngine DE;

	S = class'SevenScript'.default.Lines[i].Snd;
	Who = class'SevenScript'.default.Lines[i].Speaker;
	What = class'SevenScript'.default.Lines[i].Text;
	Dur = class'SevenScript'.default.Lines[i].Dur;

	if (S != None)
	{
		if (Radio == None)
			Radio = Spawn(class'SevenRadio');
		if (PC.Pawn != None)
			Radio.Follow(PC.Pawn);
		else
			Radio.Follow(PC);
		Radio.Say(S);
	}
	// subtitles in the game's own dialogue box, bottom centre
	if (What != "")
	{
		DE = class'DialogEngine'.static.GetInstance(Self);
		class'UIConsole'.static.BroadcastStatusMessage(Self, Who$": "$What, Dur + 0.6, DE.SubtitleFont,
			DE.SubtitleColorPlayer, , , , "DialogSubtitlesHolder", true, DE.SubtitleBoxWidth);
	}
	NextLineTime = Level.TimeSeconds + Dur;
	if (What != "")
		NextLineTime += 0.3;             // a breath between spoken lines
	Log("U2Seven: E"$Episode$" "$Who$": "$What);
}

function TickStory(float DeltaTime)
{
	local PlayerController PC;

	if (Episode == 0)
		return;
	PC = ThePlayer();
	if (PC == None)
		return;

	// the player must be in control (not in a cutscene) for a moment first
	if (PC.Pawn != None && PC.IsInState('PlayerWalking'))
		ControlTime += DeltaTime;
	else
	{
		ControlTime = 0;
		if (StoryStart > 0)
		{
			NextLineTime += DeltaTime;    // hold the radio during cutscenes
			StoryStart += DeltaTime;
		}
		return;
	}

	if (StoryStart == 0)
	{
		if (bIntroWanted && ControlTime >= 1.5)
			StartIntro();
		return;
	}

	if (Level.TimeSeconds < NextLineTime)
		return;
	if (Queue.Length > 0)
	{
		PlayLine(PC, Queue[0]);
		Queue.Remove(0, 1);
		return;
	}
	if (PendingCues.Length > 0 && Level.TimeSeconds - StoryStart >= CueStart(PendingCues[0]))
	{
		QueueCue(PendingCues[0]);
		PendingCues.Remove(0, 1);
	}
}

// silence the original dialogue listed in SevenScript.MutedNodes: no voice,
// no subtitle, over in a moment - but the node still runs, so the events it
// fires (objectives, doors) still happen. Nodes of other maps aren't loaded
// and are skipped.
function int MuteOriginal()
{
	local int i, n;
	local DialogNode DN;

	for (i = 0; i < class'SevenScript'.default.MutedNodes.Length; i++)
	{
		// node names only exist once the level's dialogue is loaded, so they
		// are kept as strings and turned into names here
		SetPropertyText("NodeName", class'SevenScript'.default.MutedNodes[i]);
		DN = class'DialogEngine'.static.GetNode(Self, NodeName);
		if (DN == None)
			continue;
		DN.Filename = "";
		DN.LongText = "";
		DN.AudioDuration = 0.4;
		DN.PreDelay = 0;
		DN.PostDelay = 0;
		n++;
	}
	return n;
}

event Tick(float DeltaTime)
{
	local int n;

	TickFlow();
	if (!bStory)
		return;
	// the dialogue files load with the level; try on the first few ticks
	if (MuteTries < 5)
	{
		MuteTries++;
		n = MuteOriginal();
		if (n > 0)
		{
			Log("U2Seven: silenced "$n$" original dialogue lines");
			MuteTries = 5;
		}
	}
	TickStory(DeltaTime);
}

defaultproperties
{
	bSevenFlow=True
	bSkipTutorial=True
	bStory=True
	bShortSanctuary=True
	LastIntroEp=0
	RemoteRole=ROLE_None
}
