r"""The dialogue as Sanctuary Open plays it, for the writer's review: every conversation OpenDirector fires, in the order
the beats fire, with where it fires (the place, what the player can see there), whether a fight is on, and each
line (speaker, sound actor, words, a spoken-length estimate). Barks listed after.

    py playlist.py     -> dialogue_playlist.md (+ .json)
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import plan as S  # noqa

GAME = r"C:\Program Files (x86)\Steam\steamapps\common\Unreal II The Awakening"
INI = os.path.join(HERE, "..", "System", "U2Sanctuary.ini")
WPS = 2.7   # spoken words per second (estimate)


def load_nodes(dirs):
    nodes = {}
    for d in dirs:
        p = os.path.join(GAME, "Dialog", d)
        for f in sorted(os.listdir(p)):
            if not f.lower().endswith(".dlg"):
                continue
            cur = None
            for line in open(os.path.join(p, f), encoding="latin1"):
                line = line.rstrip("\r\n")
                m = re.match(r"\[(.+)\]$", line)
                if m:
                    cur = nodes.setdefault(m.group(1).lower(), {"file": d + "/" + f, "name": m.group(1)})
                elif cur is not None and "=" in line:
                    k, v = line.split("=", 1)
                    k = {"nextnode": "next", "longtext": "LongText", "shorttext": "ShortText", "speaker": "Speaker",
                         "soundactor": "SoundActor"}.get(k.lower(), k)
                    cur.setdefault(k, v) if k != "next" else cur.setdefault("next", []).append(v)
    return nodes


def chain(nodes, topic):
    out, seen, n = [], set(), topic
    n = n.lower() if n else n
    while n and n in nodes and n not in seen:
        seen.add(n)
        d = nodes[n]
        txt = d.get("LongText", d.get("ShortText", ""))
        out.append({"node": d["name"], "speaker": d.get("Speaker", "?"), "sound_actor": d.get("SoundActor", ""),
                    "text": txt, "secs": round(max(1.0, len(txt.split()) / WPS), 1)})
        nx = d.get("next", [])
        n = nx[0].lower() if nx else None
    return out


def main():
    ini = open(INI, encoding="latin1").read()
    od = ini[ini.find("[U2Sanctuary.OpenDirector]"):]
    dirs = re.search(r"DialogDirs=(.*)", od).group(1).strip().split(",")
    nodes = load_nodes(dirs)
    beats = [dict(zip(("id", "x", "y", "r", "topics", "objective", "enc", "after"), m)) for m in re.findall(
        r'Beats=\(Id="(\w+)",At=\(X=([-\d.]+),Y=([-\d.]+),Z=[-\d.]+\),Radius=([\d.]+),Topics="([^"]*)",Objective="([^"]*)",Encounter="([^"]*)",After="([^"]*)"\)', od)]
    waves = re.findall(r'Waves=\(Encounter="(\w+)",Pawns="([^"]*)",Doors="[^"]*",When="([^"]*)",Delay=([\d.]+)', od)
    barks = re.search(r"Barks=(.*)", od).group(1).strip().split(",")
    places = {q["id"]: q for q in S.PLACES}

    def place_of(x, y):
        best = min(S.PLACES, key=lambda q: (q["x"] - x) ** 2 + (q["y"] - y) ** 2)
        return best

    out, L = [], ["# Sanctuary Open - the dialogue as it now plays", "",
                  "Generated by open/playlist.py from the OpenDirector section of System/U2Sanctuary.ini and the game's Dialog files. "
                  "Lines play one conversation at a time, 1.5 s apart, when the player enters the beat's radius (after the beat named in 'after'). "
                  "Seconds are estimates (%.1f words/s). NOTE: the Dialog files' Speaker field is 'Player' on almost every line (it names who "
                  "holds the conversation, not who speaks): Aida is the voice in Dalton's ear, Dalton (the player) answers, Miller speaks through "
                  "the cameras ([via LookTarget...] = a camera/sound actor in the shipped map, which the open map does not have)." % WPS, ""]
    for b in beats:
        q = place_of(float(b["x"]), float(b["y"]))
        fight = [w for w in waves if w[0] == b["enc"]]
        first = next((w for w in fight if w[2] == "enter" or w[2].startswith("t+")), None)
        conv = [{"topic": t, "lines": chain(nodes, t)} for t in b["topics"].split(",") if t]
        secs = sum(l["secs"] for c in conv for l in c["lines"])
        e = {"beat": b["id"], "place": q["id"], "place_name": q["name"], "what": q.get("what", ""), "radius": float(b["r"]),
             "after": b["after"], "objective": b["objective"], "encounter": b["enc"],
             "fight": ["%s (%s, +%ss)" % (w[1], w[2], w[3]) for w in fight], "talk_secs": round(secs, 1),
             "fight_starts_after_s": float(first[3]) if first else None, "conversations": conv}
        out.append(e)
        L += ["## %s - at %s (%s)" % (b["id"], q["name"], q["id"]), "",
              "- **The place:** %s" % q.get("what", ""),
              "- **Fires:** within %.0f UU%s" % (float(b["r"]), (", after `%s`" % b["after"]) if b["after"] else ""),
              "- **Objective shown:** %s" % (b["objective"] or "-"),
              "- **Fight started by this beat:** %s" % ("; ".join(e["fight"]) or "none"),
              "- **Talk:** about %.0f s%s" % (secs, ("  (the first wave comes %.0f s in: OVERLAP)" % float(first[3])) if first and secs > float(first[3]) else ""), ""]
        for c in conv:
            L.append("**%s**" % c["topic"])
            if not c["lines"]:
                L.append("- (topic not found in %s)" % dirs)
            for l in c["lines"]:
                L.append("- %s%s: %s  _(%.0f s)_" % (l["speaker"], (" [via %s]" % l["sound_actor"]) if l["sound_actor"] else "", l["text"], l["secs"]))
            L.append("")
    L += ["## Barks (while a fight is on: every 14-24 s, 60 % chance, one at random)", ""]
    bk = []
    for t in barks:
        ls = chain(nodes, t)
        bk.append({"topic": t, "lines": ls})
        L.append("**%s**" % t)
        L += ["- %s: %s" % (l["speaker"], l["text"]) for l in ls] + [""]
    json.dump({"beats": out, "barks": bk}, open(os.path.join(HERE, "dialogue_playlist.json"), "w"), indent=1)
    open(os.path.join(HERE, "dialogue_playlist.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("%d beats, %d conversations, %d barks -> dialogue_playlist.md" % (len(out), sum(len(e["conversations"]) for e in out), len(bk)))


if __name__ == "__main__":
    main()
