"""Writes AdventMod/Classes/ModSkins.uc: for each character mesh, the skin materials it wears
by default (slot by slot), as full object paths. Script can't ask a mesh for its materials,
and most characters set no Skins of their own, so anything that has to re-dress a body
(ModBloodCoat's blood-stained skins) looks them up here.

The meshes' material names come from our own exports (Documents/AdventRising_meshes/*.txt,
tools/ukx_mesh.py); the paths from the game's character texture packages.

    python tools/gen_skins.py
"""
import glob
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from ukx import Package   # noqa: E402

GAME = r"H:\SteamLibrary\steamapps\common\Advent Rising"
MESHES = os.path.join(os.path.expanduser("~"), "Documents", "AdventRising_meshes")
UC = os.path.join(HERE, "..", "AdventMod", "Classes", "ModSkins.uc")
TEMPLATE = """//=============================================================================
// ModSkins - the skin materials each character mesh wears by default, slot by slot (full
// object paths, loaded when needed). Generated by tools/gen_skins.py: don't edit by hand.
//=============================================================================
class ModSkins extends Object;

struct MeshSkins
{
	var string Mesh;       // the mesh's name, in capitals
	var string Skin[4];
};
var array<MeshSkins> Meshes;

// the entry for a mesh (-1 none)
static function int Find(Mesh M)
{
	local string N;
	local int i;

	if (M == None)
		return -1;
	N = Caps(string(M.Name));
	for (i = 0; i < default.Meshes.Length; i++)
		if (default.Meshes[i].Mesh == N)
			return i;
	return -1;
}

defaultproperties
{
%s
}
"""


def pick(candidates, mesh):
    """the same material name can be in several packages: the mesh's own kind first"""
    if not candidates:
        return ""
    order = ["seeker", "aurelian", "human", "extra"]
    if "SEEKER" in mesh:
        order = ["seeker", "extra", "human", "aurelian"]
    elif "AURELIAN" in mesh:
        order = ["aurelian", "extra", "human", "seeker"]
    else:
        order = ["human", "extra", "seeker", "aurelian"]
    return sorted(candidates, key=lambda c: next((i for i, o in enumerate(order) if c.lower().startswith(o)), 9))[0]


def main():
    paths = {}
    for pkg in sorted(glob.glob(os.path.join(GAME, "Textures", "*characters_tx.utx"))):
        p = Package(pkg)
        base = os.path.splitext(os.path.basename(pkg))[0]
        for e in p.exports:
            cls = p.cls(e)
            if "Shader" not in cls and "Material" not in cls:
                continue
            chain, outer = [e["name"]], e["outer"]
            while outer > 0:
                o = p.exports[outer - 1]
                chain.append(o["name"])
                outer = o["outer"]
            paths.setdefault(e["name"].lower(), []).append(base + "." + ".".join(reversed(chain)))
    rows = []
    for txt in sorted(glob.glob(os.path.join(MESHES, "*.txt"))):
        mats = []
        for line in open(txt, encoding="utf-8", errors="replace"):
            if line.startswith("materials:"):
                mats = [m.strip() for m in line.split(":", 1)[1].split(",") if m.strip()]
                break
        name = os.path.splitext(os.path.basename(txt))[0].upper()
        found = [pick(paths.get(m.lower(), []), name) for m in mats[:4]]
        if not mats or not all(found):
            continue
        skins = ",".join('Skin[%d]="%s"' % (i, s) for i, s in enumerate(found))
        rows.append('     Meshes(%d)=(Mesh="%s",%s)' % (len(rows), name, skins))
    open(UC, "w", newline="\r\n").write(TEMPLATE % "\n".join(rows))
    print(UC, len(rows), "meshes,", len(paths), "materials known")


if __name__ == "__main__":
    main()
