"""Writes AdventMod/Classes/ModGibParts.uc from GibSplit's manifests: an #exec import per
gib part (the .ase files that build.ps1 stages into <game>\\AdventMod\\Gibs) and a table of
the parts (set, mesh, pivot, size, mass) for ModGore.

    python gen_gibs.py <gibs dir> <set:skin path> ...
    e.g. python gen_gibs.py C:\\...\\AdventRising_meshes\\gibs marine:humancharacters_tx.secondary.marine_hsh

The pivots are turned from the psk's space (Y down, feet at 0) into Z up: X side, Y the
mesh's forward, Z height above the feet.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "AdventMod", "Classes", "ModGibParts.uc")


def main():
    gibs = sys.argv[1]
    execs, parts, sets = [], [], []
    for arg in sys.argv[2:]:
        name, skin = arg.split(":", 1)
        man = json.load(open(os.path.join(gibs, name, name + "_gibs.json")))
        top = 0.0
        for p in man["parts"]:
            mesh = p["file"][:-4]
            x, y, z = p["pivot_mesh"]
            up = -y
            top = max(top, up + p["size"][2] / 2)
            execs.append("#exec NEW StaticMesh FILE=Gibs\\%s NAME=%s GROUP=Gibs" % (p["file"], mesh))
            parts.append("     Parts(%d)=(Set=%s,Mesh=StaticMesh'AdventMod.Gibs.%s',Pivot=(X=%.2f,Y=%.2f,Z=%.2f),Size=(X=%.2f,Y=%.2f,Z=%.2f),Mass=%.2f)"
                         % (len(parts), name, mesh, x, z, up, p["size"][0], p["size"][1], p["size"][2], p["mass_kg"]))
        sets.append("     Sets(%d)=(Name=%s,Skin=\"%s\",Height=%.1f)" % (len(sets), name, skin, top))
    src = """//=============================================================================
// ModGibParts - the gib parts: static meshes cut from the game's own character
// meshes (tools/ukx_mesh.py -> .psk -> GibSplit -> .ase), imported into AdventMod.u,
// group Gibs, and their table for ModGore. Generated by tools/gen_gibs.py: don't
// edit by hand.
//   Pivot: the part's centre on the standing character, Z up from the feet, X to
//   the side, Y the mesh's forward. Height: the set's standing height (to scale it
//   to the victim). Skin: the material whose Diffuse the parts wear (slot 0; slot 1
//   is the meat on the cuts).
//=============================================================================
class ModGibParts extends Object;

%s

struct GibPart
{
	var name Set;
	var StaticMesh Mesh;
	var vector Pivot, Size;
	var float Mass;
};

struct GibSet
{
	var name Name;
	var string Skin;
	var float Height;
};

var array<GibPart> Parts;
var array<GibSet> Sets;

defaultproperties
{
%s
%s
}
""" % ("\n".join(execs), "\n".join(parts), "\n".join(sets))
    open(OUT, "w", newline="\r\n").write(src)
    print(OUT, len(parts), "parts in", len(sets), "sets")


if __name__ == "__main__":
    main()
