"""Writes AdventMod/Classes/ModJiggleBones.uc from the jiggle fit (JIGGLE.md): per jiggle bone its
parent, lever (parent frame), max amplitude and spring parameters; numbers only, so it is committed.

    py -I tools/make_jiggle_uc.py <jiggle dir>/jiggle_fit.json

The springs in the table are NOT the fitted ones: the fit (fit_report.md) does not identify a
second-order response in the soft-body reference (its error equals the signal for nearly every
bone and clip), so the live springs are set by hand at a flesh-like 3.5 Hz, damping ratio 0.3, and
scaled per bone by what the reference measured: the max amplitude is the reference's 95th
percentile angle (x1.3, clamped 8..30 deg) and the gain follows the bone's share of the
reference's motion over the run and the two hit clips (the mean bone gets GAIN_MEAN). The raw fit
is kept in the table (FitK/FitD/FitGain) for a later look.
"""
import json
import math
import os
import sys

F0 = 3.5            # Hz
ZETA = 0.3
GAIN_MEAN = 0.25
REF_CLIPS = ("Run", "R_Front", "R_Back")
UC = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "AdventMod", "Classes", "ModJiggleBones.uc")

TEMPLATE = """//=============================================================================
// ModJiggleBones - the Seeker infantry's jiggle bones (JIGGLE.md): parent, lever (the region's
// centre in the parent's frame), the live spring per bone (k, d, gain, max amplitude) and, for
// the record, the raw fit to the soft-body reference. Generated by tools/make_jiggle_uc.py from
// the fit's JSON: don't edit by hand. ModJiggle sends them to the DLL (JiggleBone lines).
//=============================================================================
class ModJiggleBones extends Object;

var name Names[16];
var string Parents[16];
var vector Lever[16];
var float K[16];
var float D[16];
var float Gain[16];
var float MaxDeg[16];
var float FitK[16];
var float FitD[16];
var float FitGain[16];
var int Count;

defaultproperties
{
%s
}
"""


def main():
    fit = json.load(open(sys.argv[1]))
    bones = fit["bones"]
    k = (2 * math.pi * F0) ** 2
    d = 2 * ZETA * math.sqrt(k)
    share = {}
    for name, b in bones.items():
        lev = math.sqrt(sum(x * x for x in b["lever"]))
        vals = [math.radians(b["clips"][c]["signal_rms_deg"]) * lev for c in REF_CLIPS if c in b["clips"]]
        share[name] = sum(vals) / max(len(vals), 1)
    mean = sum(share.values()) / max(len(share), 1)
    lines = []
    for i, (name, b) in enumerate(bones.items()):
        maxdeg = min(30.0, max(8.0, b["max_deg"] * 1.3))
        gain = GAIN_MEAN * share[name] / mean if mean > 0 else GAIN_MEAN
        lines += ['     Names(%d)=%s' % (i, name), '     Parents(%d)="%s"' % (i, b["parent"]),
                  "     Lever(%d)=(X=%.3f,Y=%.3f,Z=%.3f)" % (i, *b["lever"]),
                  "     K(%d)=%.3f" % (i, k), "     D(%d)=%.3f" % (i, d), "     Gain(%d)=%.4f" % (i, gain), "     MaxDeg(%d)=%.2f" % (i, maxdeg),
                  "     FitK(%d)=%.3f" % (i, b["k"]), "     FitD(%d)=%.3f" % (i, b["d"]), "     FitGain(%d)=%.4f" % (i, b["gain"])]
        print("%-14s %-16s lever %5.1f  max %5.1f deg  gain %.3f  (ref motion at the tip %.2f u; fit k %.0f d %.1f gain %.3f)" % (name, b["parent"], math.sqrt(sum(x * x for x in b["lever"])), maxdeg, gain, share[name], b["k"], b["d"], b["gain"]))
    lines.append("     Count=%d" % len(bones))
    open(UC, "w", newline="\r\n").write(TEMPLATE % "\n".join(lines))
    print("wrote", os.path.normpath(UC), "k %.1f d %.2f (%.1f Hz, zeta %.2f)" % (k, d, F0, ZETA))


if __name__ == "__main__":
    main()
