"""Build the HoverTest assets and map in UnrealEd through U2EdBridge.

    python make_map.py              generate meshes, textures, hills_actors.t3d
    python build_editor.py assets   static meshes/textures -> StaticMeshes/HoverTestSM.usx,
                                    U2HoverSM.usx (the bike); brushes/room.u3d
    python build_editor.py map      Maps/HoverTest.un2, then paths

Each step runs in a fresh editor (UnrealEd crashes if a map is imported after
MAP NEW in the same session, and its path builder crashes in the import
session).
"""
import os, sys

sys.path.insert(0, r"C:\Users\john\Documents\github\codes\tools\C\U2EdBridge")
import u2ed

GAME = r"C:\PROGRA~2\Steam\STEAMA~1\common\UNREAL~2"   # 8.3: Unreal paths can't contain spaces
H = GAME + r"\U2Hover"
SM = GAME + r"\StaticMeshes"
MAPS = GAME + r"\Maps"

TILES = 5
PF_FAKEBACKDROP = 0x80

ASSETS = [
    r'NEW StaticMeshFactory PACKAGE="HoverTestSM" GROUP="Ground" NAME="Hills%d%d" FILE="{H}\Models\ase\Hills%d%d.ase"'
    % (i, j, i, j) for i in range(TILES) for j in range(TILES)
] + [
    r'NEW StaticMeshFactory PACKAGE="HoverTestSM" GROUP="Ground" NAME="River" FILE="{H}\Models\ase\River.ase"',
    r'NEW StaticMeshFactory PACKAGE="HoverTestSM" GROUP="Sky" NAME="SkyBox" FILE="{H}\Models\ase\SkyBox.ase"',
    r'TEXTURE IMPORT FILE="{H}\Textures\HillGrass.tga" NAME="HillGrass" PACKAGE="HoverTestSM" GROUP="Ground" MIPS=1',
    r'TEXTURE IMPORT FILE="{H}\Textures\SkyAtlas.tga" NAME="SkyAtlas" PACKAGE="HoverTestSM" GROUP="Sky" MIPS=0',
    r'OBJ SAVEPACKAGE PACKAGE="HoverTestSM" FILE="{SM}\HoverTestSM.usx"',
    r'NEW StaticMeshFactory PACKAGE="U2HoverSM" GROUP="Manta" NAME="MantaBody" FILE="{H}\Models\ase\MantaBody000.ase"',
    r'OBJ SAVEPACKAGE PACKAGE="U2HoverSM" FILE="{SM}\U2HoverSM.usx"',
    # the main room brush: the stock Entry map's builder brush (a 512-unit cube,
    # saved by brush_survey.py) scaled to 20480 x 20480 x 6144. Scaling only
    # works on selected brushes, and only the builder exists in a fresh editor.
    r'BRUSH LOAD FILE="{H}\brushes\Entry.u3d"',
    r'ACTOR SELECT ALL',
    r'BRUSH SCALE X=40 Y=40 Z=12',
    r'BRUSH SAVE FILE="{H}\brushes\room.u3d"',
]

MAP = [
    r'OBJ LOAD FILE="{SM}\HoverTestSM.usx"',
    r'OBJ LOAD FILE="{SM}\Mission_05M.usx"',
    r'OBJ LOAD FILE="{GAME}\Textures\ScottT.utx"',
    r'OBJ LOAD FILE="{GAME}\Textures\Mission_10T.utx"',
    r'OBJ LOAD FILE="{GAME}\Textures\JungleT.utx"',
    # main room; every surface shows the sky zone (fake backdrop)
    r'BRUSH LOAD FILE="{H}\brushes\room.u3d"',
    r'BRUSH MOVETO X=0 Y=0 Z=0',
    r'BRUSH SUBTRACT',
    r'MAP REBUILD',
    r'POLY SELECT ALL',
    r'POLY SET SETFLAGS=%d' % PF_FAKEBACKDROP,
    r'POLY SELECT NONE',
    # the sky zone: a sealed 512-unit room far above, carved after the flags
    r'BRUSH LOAD FILE="{H}\brushes\Entry.u3d"',
    r'BRUSH MOVETO X=0 Y=0 Z=10000',
    r'BRUSH SUBTRACT',
    r'MAP IMPORTADD FILE="{H}\hills_actors.t3d"',
    r'MAP REBUILD',
    r'LIGHT APPLY',
    r'MAP SAVE FILE="{MAPS}\HoverTest.un2"',
]

# the game finds PlayerStarts through the navigation list; PATHS BUILD crashes
# (scout controller), PATHS DEFINE is enough to register the start
PATHS = [
    r'MAP LOAD FILE="{MAPS}\HoverTest.un2"',
    r'PATHS DEFINE',
    r'MAP SAVE FILE="{MAPS}\HoverTest.un2"',
]


def run(cmds):
    ed = u2ed.Editor.start()
    try:
        # everything these sessions save is generated by us: let "overwrite?" through
        ed.exec("!answer yes")
        for c in cmds:
            c = c.format(H=H, SM=SM, MAPS=MAPS, GAME=GAME)
            try:
                rc, out = ed.exec_rc(c)
            except u2ed.EditorCrashed as e:
                print("CRASH during", c, "\n", e)
                return False
            lines = out.strip().splitlines()
            print("== %s  [rc=%d, %d lines]" % (c, rc, len(lines)))
            for l in lines[-3:]:
                print("     " + l)
        return True
    finally:
        ed.stop()


if __name__ == "__main__":
    step = sys.argv[1] if len(sys.argv) > 1 else "assets"
    if step == "assets":
        ok = run(ASSETS)
    elif step == "map":
        ok = run(MAP) and run(PATHS)
    else:
        ok = run(PATHS)
    sys.exit(0 if ok else 1)
