pcss=1
posthud=z0
post=1
bloom=0.6 0.5
grade=1.0 1.0 1.0 0.25
colour=1 1 1
sharpen=0.4
postfx=0.0015 0.02 1 0.76
lut=lut_advent.bmp
smaa=1
psreplace=6c86c52f terrain3.hlsl
terrainfx=0.2 1 0.08 0
pbr=2e106041 gideon_uniform_pbr.dds 1.8 1.6
decal=b05701c2 decal_parallax.hlsl
decal=2cbc6675 decal_parallax.hlsl
decal=b23370d1 decal_parallax.hlsl
decal=7bb06894 decal_parallax.hlsl
decal=25157f2f decal_parallax.hlsl
decal=94744b3b decal_parallax.hlsl
# blood pool frames (tools/make_blood_pool.py): the pool's middle sinks in a little
decal=2be19d45 decal_parallax.hlsl
decal=54b64252 decal_parallax.hlsl
decal=b663d9d7 decal_parallax.hlsl
decal=8dee559c decal_parallax.hlsl
decal=13cb57bb decal_parallax.hlsl
decal=bcfc70fc decal_parallax.hlsl
decal=b0816215 decal_parallax.hlsl
decal=60704432 decal_parallax.hlsl
decal=cfc738c1 decal_parallax.hlsl
