//=============================================================================
// RigBike - a HoverBike drawn as a rig of rigid parts that play the vehicle's
// own (UT3) animations: Unreal II's skeletal meshes are Golem-only, but UT3
// vehicles are rigidly skinned, so one static mesh per bone moved by script
// reproduces them exactly.
//
// Data (generated by tools/python/U2Golem/vehicle_parts.py into a subclass):
//   Bones   the skeleton: parent index, parent-relative rest transform, and
//           which part (if any) the bone carries
//   Seqs    the animation sequences; Keys holds Frames x Bones.Length
//           parent-relative transforms per sequence, starting at First
// Each tick the bone chain is composed in vehicle space (parents first, as
// the generator writes them), then every part is put at its bone.
// Live overrides: AimYawBone / AimPitchBone turn toward where the driver
// looks; Alt Fire plays DeploySeq, holds HoldSeq, and RetractSeq on release.
//=============================================================================
class RigBike extends HoverBike
	abstract;

struct RigBone
{
	var string BoneName;
	var int    Parent;
	var vector L;
	var rotator R;
	var int    Part;
};
struct RigSeq
{
	var string SeqName;
	var int    First;
	var int    Frames;
	var float  Rate;
};
struct RigKey
{
	var vector L;
	var rotator R;
};

var() array<RigBone>  Bones;
var() array<string>   PartMeshes;
var() array<RigSeq>   Seqs;
var() array<RigKey>   Keys;
var() string IdleSeq, DeploySeq, HoldSeq, RetractSeq;
var() string AimYawBone, AimPitchBone;
var() float  AimRate;            // yaw units per second the turret turns

var array<RigPart> Parts;
var array<vector>  BX, BY, BZ, BP;   // composed bone frames, vehicle space
var int   CurSeq, NextSeq;
var float SeqTime;
var bool  bHoldLast;
var int   AimYawIdx, AimPitchIdx;
var int   AimYaw, AimPitch;
var bool  bDeployed;

simulated event PostBeginPlay()
{
	local int i;
	local Material Skin;

	Super.PostBeginPlay();
	if (BodySkin != "")
		Skin = Material(DynamicLoadObject(BodySkin, class'Material'));
	Parts.Length = PartMeshes.Length;
	for (i = 0; i < PartMeshes.Length; i++)
	{
		Parts[i] = Spawn(class'RigPart', self, , Location, Rotation);
		if (Parts[i] != None)
		{
			Parts[i].SetMesh(StaticMesh(DynamicLoadObject(PartMeshes[i], class'StaticMesh')));
			if (Skin != None)
				Parts[i].Skins[0] = Skin;
		}
	}
	BX.Length = Bones.Length;
	BY.Length = Bones.Length;
	BZ.Length = Bones.Length;
	BP.Length = Bones.Length;
	AimYawIdx = FindBone(AimYawBone);
	AimPitchIdx = FindBone(AimPitchBone);
	PlaySeq(IdleSeq, true);
	UpdateRig(0);
}

simulated event Destroyed()
{
	local int i;
	for (i = 0; i < Parts.Length; i++)
		if (Parts[i] != None)
			Parts[i].Destroy();
	Super.Destroyed();
}

function int FindBone(string N)
{
	local int i;
	if (N == "")
		return -1;
	for (i = 0; i < Bones.Length; i++)
		if (Bones[i].BoneName ~= N)
			return i;
	return -1;
}

function int FindSeq(string N)
{
	local int i;
	for (i = 0; i < Seqs.Length; i++)
		if (Seqs[i].SeqName ~= N)
			return i;
	return -1;
}

// start a sequence; bHold keeps its last frame when it ends (else it loops)
function PlaySeq(string N, bool bHold)
{
	local int s;
	s = FindSeq(N);
	if (s < 0)
		return;
	CurSeq = s;
	SeqTime = 0;
	bHoldLast = bHold;
}

function int RotDelta(int A, int B)
{
	local int d;
	d = (B - A) & 65535;
	if (d > 32767)
		d -= 65536;
	return d;
}

// rotate v about Z (yaw units)
function vector RotZ(vector v, int Ang)
{
	local float c, s;
	local vector o;
	c = Cos(Ang * Pi / 32768.0);
	s = Sin(Ang * Pi / 32768.0);
	o.X = v.X * c - v.Y * s;
	o.Y = v.X * s + v.Y * c;
	o.Z = v.Z;
	return o;
}

// rotate v about Y (pitch units, nose up for positive like Unreal pitch)
function vector RotY(vector v, int Ang)
{
	local float c, s;
	local vector o;
	c = Cos(Ang * Pi / 32768.0);
	s = Sin(Ang * Pi / 32768.0);
	o.X = v.X * c - v.Z * s;
	o.Z = v.X * s + v.Z * c;
	o.Y = v.Y;
	return o;
}

simulated function UpdateRig(float Delta)
{
	local int i, f0, f1, k0, k1, nb;
	local float t;
	local vector L, lx, ly, lz, VX, VY, VZ, P, X, Y, Z;
	local rotator R;

	nb = Bones.Length;
	if (nb == 0 || CurSeq < 0 || CurSeq >= Seqs.Length)
		return;

	// advance the sequence; hold, loop or chain to NextSeq
	SeqTime += Delta * Seqs[CurSeq].Rate;
	if (SeqTime >= Seqs[CurSeq].Frames - 1)
	{
		if (bHoldLast || Seqs[CurSeq].Frames <= 1)
			SeqTime = Seqs[CurSeq].Frames - 1;
		else
			SeqTime = 0;
	}
	f0 = int(SeqTime);
	f1 = Min(f0 + 1, Seqs[CurSeq].Frames - 1);
	t = SeqTime - f0;

	for (i = 0; i < nb; i++)
	{
		k0 = (Seqs[CurSeq].First + f0) * nb + i;
		k1 = (Seqs[CurSeq].First + f1) * nb + i;
		L = Keys[k0].L + (Keys[k1].L - Keys[k0].L) * t;
		R.Pitch = Keys[k0].R.Pitch + int(RotDelta(Keys[k0].R.Pitch, Keys[k1].R.Pitch) * t);
		R.Yaw   = Keys[k0].R.Yaw   + int(RotDelta(Keys[k0].R.Yaw,   Keys[k1].R.Yaw)   * t);
		R.Roll  = Keys[k0].R.Roll  + int(RotDelta(Keys[k0].R.Roll,  Keys[k1].R.Roll)  * t);
		GetAxes(R, lx, ly, lz);
		// live turret aim, applied in the parent's frame about the bone's own pivot
		if (i == AimYawIdx)
		{
			lx = RotZ(lx, AimYaw);
			ly = RotZ(ly, AimYaw);
			lz = RotZ(lz, AimYaw);
		}
		else if (i == AimPitchIdx)
		{
			lx = RotY(lx, AimPitch);
			ly = RotY(ly, AimPitch);
			lz = RotY(lz, AimPitch);
		}
		if (Bones[i].Parent < 0)
		{
			BX[i] = lx;
			BY[i] = ly;
			BZ[i] = lz;
			BP[i] = L;
		}
		else
		{
			BX[i] = lx.X * BX[Bones[i].Parent] + lx.Y * BY[Bones[i].Parent] + lx.Z * BZ[Bones[i].Parent];
			BY[i] = ly.X * BX[Bones[i].Parent] + ly.Y * BY[Bones[i].Parent] + ly.Z * BZ[Bones[i].Parent];
			BZ[i] = lz.X * BX[Bones[i].Parent] + lz.Y * BY[Bones[i].Parent] + lz.Z * BZ[Bones[i].Parent];
			BP[i] = BP[Bones[i].Parent] + L.X * BX[Bones[i].Parent] + L.Y * BY[Bones[i].Parent] + L.Z * BZ[Bones[i].Parent];
		}
	}

	// vehicle space -> world, then place the parts
	GetAxes(Rotation, VX, VY, VZ);
	for (i = 0; i < nb; i++)
	{
		if (Bones[i].Part < 0 || Bones[i].Part >= Parts.Length || Parts[Bones[i].Part] == None)
			continue;
		P = Location + BP[i].X * VX + BP[i].Y * VY + BP[i].Z * VZ;
		X = BX[i].X * VX + BX[i].Y * VY + BX[i].Z * VZ;
		Y = BY[i].X * VX + BY[i].Y * VY + BY[i].Z * VZ;
		Z = BZ[i].X * VX + BZ[i].Y * VY + BZ[i].Z * VZ;
		Parts[Bones[i].Part].SetLocation(P);
		Parts[Bones[i].Part].SetRotation(OrthoRotation(X, Y, Z));
	}
}

event Tick(float Delta)
{
	local Controller C;
	local int Want;

	Super.Tick(Delta);

	if (DriverPawn != None)
		C = DriverPawn.Controller;
	if (C != None)
	{
		// turret follows the view, at AimRate
		Want = RotDelta(Rotation.Yaw, C.Rotation.Yaw);
		AimYaw += Clamp(RotDelta(AimYaw, Want), -int(AimRate * Delta), int(AimRate * Delta));
		Want = Clamp(RotDelta(0, C.Rotation.Pitch), -6000, 4000);
		AimPitch += Clamp(RotDelta(AimPitch, Want), -int(AimRate * Delta), int(AimRate * Delta));
		// Alt Fire: deploy and hold; release: retract
		if (C.bAltFire != 0 && !bDeployed && DeploySeq != "")
		{
			bDeployed = true;
			PlaySeq(DeploySeq, true);
		}
		else if (C.bAltFire == 0 && bDeployed)
		{
			bDeployed = false;
			PlaySeq(RetractSeq, true);
		}
	}
	else
	{
		AimYaw += Clamp(RotDelta(AimYaw, 0), -int(AimRate * Delta), int(AimRate * Delta));
		AimPitch += Clamp(RotDelta(AimPitch, 0), -int(AimRate * Delta), int(AimRate * Delta));
		if (bDeployed)
		{
			bDeployed = false;
			PlaySeq(RetractSeq, true);
		}
	}
	UpdateRig(Delta);
}

defaultproperties
{
	BodyMesh=""
	DrawType=DT_None
	DrawScale=1.000000
	bNoStaticMeshCollide=True
	bAltFireHops=False
	IdleSeq="Idle"
	AimRate=30000.000000
	CurSeq=-1
	AimYawIdx=-1
	AimPitchIdx=-1
}
