"""Writes terrain3.hlsl and terrain4.hlsl (3- and 4-layer terrain) from terrain_src.hlsl:
the U2Shaders layer compiles single files without includes. Run after editing the source."""
import os
here = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(here, 'terrain_src.hlsl'), encoding='utf-8').read()
for n in (3, 4):
    out = '// GENERATED by make_terrain.py from terrain_src.hlsl - edit that file\n#define LAYERS %d\n' % n + src
    open(os.path.join(here, 'terrain%d.hlsl' % n), 'w', encoding='utf-8').write(out)
    print('wrote terrain%d.hlsl' % n)
