//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 Dry;
//   float4 Env;
//   float4 Fx;
//   float4 Info;
//   float4 Light[8];
//   float4 Mode;
//   float4 Proj[4];
//   sampler2D Scene;
//   sampler2D Tex;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   Info         c0       1
//   Mode         c1       1
//   Fx           c2       1
//   Env          c3       1
//   Proj         c4       4
//   Light        c8       8
//   Dry          c16      1
//   Tex          s0       1
//   Scene        s1       1
//

    ps_2_x
    def c17, 0.300000012, 0.589999974, 0.109999999, -9.99999975e-005
    def c18, 0.5, 1, -0.5, 0.850000024
    def c19, 10000, 6, -0.00100000005, 999.999939
    def c20, 4, 0.980000019, 0.0199999996, 8
    def c21, 2, 3, -0.0199999996, -0.449999988
    def c22, -0.00100000005, -1, 0, 3
    def c23, 0.00999999978, 0.00600000005, 0, 1
    def c24, 0.150000006, 0.349999994, 0.600000024, 1
    dcl t0.xyz
    dcl t2.xyz
    dcl_2d s0
    dcl_2d s1
    mov r0, c18
    mul r0.w, r0.w, c1.z
    rcp r0.w, r0.w
    rcp r1.w, t0.z
    mul r1.xy, r1.w, t0
    add r1.zw, r0.xyxy, -c1.xyxw
    cmp r1.xy, r1.z, t0, r1
    dsy r2.xyz, t2
    dsx r3.xyz, t2
    mul r4.xyz, r2.yzxw, r3.zxyw
    mad r4.xyz, r3.yzxw, r2.zxyw, -r4
    nrm r5.xyz, r4
    nrm r4.xyz, -t2
    dp3 r2.w, r5, r4
    cmp r5.xyz, r2.w, r5, -r5
    dp3 r2.w, -r4, r5
    add r2.w, r2.w, r2.w
    mad r6.xyz, r5, -r2.w, -r4
    mov r7.yz, c16
    mul r8, r7.z, c24
    mad r7.xzw, r6.xyyz, r8.x, t2.xyyz
    mul r9.xyz, r7.z, c5.xyww
    mad r9.xyz, r7.x, c4.xyww, r9
    mad r7.xzw, r7.w, c6.xyyw, r9.xyyz
    add r7.xzw, r7, c7.xyyw
    rcp r2.w, r7.w
    add r9.xy, r7.w, c22
    cmp r2.w, r9.x, r2.w, c19.w
    mul r7.xz, r2.w, r7
    mad r7.xz, r7, c18, c18.x
    mad r10.xy, c0.zwzw, r0.x, r7.xzzw
    texld r11, r1, s0
    texld r12, r10, s1
    dp3 r2.w, r11, c17
    add r2.w, -r2.w, c1.z
    mul_sat r0.w, r0.w, r2.w
    add r2.w, r0.z, c1.y
    cmp r2.w, r2.w, r0.w, r11.w
    dsy r3.w, r2.w
    dp3 r4.w, r2, r5
    mad r1.xyz, r5, -r4.w, r2
    mul r2.xyz, r3.w, r1
    dp3 r3.w, r1, r1
    add r4.w, r3.w, c17.w
    rcp r3.w, r3.w
    cmp r3.w, r4.w, r3.w, c19.x
    mul r1.xyz, r2, r3.w
    dsx r3.w, r2.w
    dp3 r4.w, r3, r5
    mad r2.xyz, r5, -r4.w, r3
    mul r3.xyz, r3.w, r2
    dp3 r3.w, r2, r2
    add r4.w, r3.w, c17.w
    rcp r3.w, r3.w
    cmp r3.w, r4.w, r3.w, c19.x
    mad r1.xyz, r3, r3.w, r1
    mad r1.xyz, r1, -c19.y, r5
    nrm r2.xyz, r1
    add r1.xyz, -t2, c10
    cmp r1.xyz, -c10.w, c10, r1
    dp3 r4.w, r1, r1
    rsq r4.w, r4.w
    rcp r6.w, r4.w
    add r12.w, r6.w, c19.z
    cmp r4.w, r12.w, r4.w, c19.w
    mad r3.xyz, r1, r4.w, r4
    mul r1.xyz, r1, r4.w
    dp3 r3.w, r2, r1
    mul_sat r3.w, r3.w, c20.x
    nrm r1.xyz, r3
    dp3_sat r4.w, r2, r1
    pow r12.w, r4.w, c2.y
    mul r4.w, r3.w, r12.w
    rcp r12.w, c10.w
    mad_sat r6.w, r6.w, -r12.w, c18.y
    cmp r6.w, -c10.w, r0.y, r6.w
    mul r6.w, r6.w, r6.w
    mul r4.w, r4.w, r6.w
    mul r4.w, r4.w, c11.w
    mul r1.xyz, r4.w, c11
    add r3.xyz, -t2, c8
    cmp r3.xyz, -c8.w, c8, r3
    dp3 r3.w, r3, r3
    rsq r3.w, r3.w
    rcp r4.w, r3.w
    add r6.w, r4.w, c19.z
    cmp r3.w, r6.w, r3.w, c19.w
    mad r5.xyz, r3, r3.w, r4
    mul r3.xyz, r3.w, r3
    dp3 r5.w, r2, r3
    mul_sat r5.w, r5.w, c20.x
    nrm r3.xyz, r5
    dp3_sat r6.w, r2, r3
    pow r12.w, r6.w, c2.y
    mul r6.w, r5.w, r12.w
    rcp r12.w, c8.w
    mad_sat r4.w, r4.w, -r12.w, c18.y
    cmp r4.w, -c8.w, r0.y, r4.w
    mul r4.w, r4.w, r4.w
    mul r4.w, r4.w, r6.w
    mul r4.w, r4.w, c9.w
    mad r1.xyz, c9, r4.w, r1
    add r3.xyz, -t2, c12
    cmp r3.xyz, -c12.w, c12, r3
    dp3 r3.w, r3, r3
    rsq r3.w, r3.w
    rcp r4.w, r3.w
    add r6.w, r4.w, c19.z
    cmp r3.w, r6.w, r3.w, c19.w
    mad r5.xyz, r3, r3.w, r4
    mul r3.xyz, r3.w, r3
    dp3 r5.w, r2, r3
    mul_sat r5.w, r5.w, c20.x
    nrm r3.xyz, r5
    dp3_sat r6.w, r2, r3
    pow r12.w, r6.w, c2.y
    mul r6.w, r5.w, r12.w
    rcp r12.w, c12.w
    mad_sat r4.w, r4.w, -r12.w, c18.y
    cmp r4.w, -c12.w, r0.y, r4.w
    mul r4.w, r4.w, r4.w
    mul r4.w, r4.w, r6.w
    mul r4.w, r4.w, c13.w
    mad r1.xyz, c13, r4.w, r1
    add r3.xyz, -t2, c14
    cmp r3.xyz, -c14.w, c14, r3
    dp3 r3.w, r3, r3
    rsq r3.w, r3.w
    rcp r4.w, r3.w
    add r6.w, r4.w, c19.z
    cmp r3.w, r6.w, r3.w, c19.w
    mad r5.xyz, r3, r3.w, r4
    mul r3.xyz, r3.w, r3
    dp3 r5.w, r2, r3
    mul_sat r5.w, r5.w, c20.x
    nrm r3.xyz, r5
    dp3_sat r6.w, r2, r3
    dp3_sat r12.w, r2, r4
    add r12.w, -r12.w, c18.y
    pow r0.z, r6.w, c2.y
    mul r6.w, r5.w, r0.z
    rcp r0.z, c14.w
    mad_sat r0.z, r4.w, -r0.z, c18.y
    cmp r0.z, -c14.w, r0.y, r0.z
    mul r0.z, r0.z, r0.z
    mul r6.w, r0.z, r6.w
    mul r6.w, r6.w, c15.w
    mad r1.xyz, c15, r6.w, r1
    mul r6.w, r12.w, r12.w
    mul r6.w, r6.w, r6.w
    mul r6.w, r6.w, r12.w
    mad r6.w, r6.w, c20.y, c20.z
    mul r12.w, r6.w, c3.w
    mul r6.w, r6.w, c16.y
    mul r2.xyz, r12.w, c3
    mul r2.xyz, r2, c2.w
    mad r1.xyz, r1, c2.z, r2
    add r0.zw, -r10.xyxy, c18.y
    min r2.xy, r0.zwzw, r10
    mul_sat r0.zw, r2.xyxy, c20.w
    mul r12.w, r0.w, r0.z
    cmp r12.w, r9.y, r12.w, c22.z
    mad r2.xyz, r6, r8.y, t2
    mul r3.xyz, r2.y, c5.xyww
    mad r3.xyz, r2.x, c4.xyww, r3
    mad r2.xyz, r2.z, c6.xyww, r3
    add r2.xyz, r2, c7.xyww
    rcp r0.z, r2.z
    add r3.xy, r2.z, c22
    cmp r0.z, r3.x, r0.z, c19.w
    mul r0.zw, r0.z, r2.xyxy
    mul r2.xy, r0.x, c0.zwzw
    mad r0.xz, r0.zyww, c18, r2.xyyw
    add r4.xy, r0.xzzw, c18.x
    add r0.xz, -r4.xyyw, c18.y
    min r3.xz, r0, r4.xyyw
    mad r0.xzw, r6.xyyz, r8.z, t2.xyyz
    mad r5.xyz, r6, r8.w, t2
    mul r6.xyz, r0.z, c5.xyww
    mad r6.xyz, r0.x, c4.xyww, r6
    mad r0.xzw, r0.w, c6.xyyw, r6.xyyz
    add r0.xzw, r0, c7.xyyw
    rcp r3.w, r0.w
    add r4.zw, r0.w, c22.xyxy
    cmp r0.w, r4.z, r3.w, c19.w
    mul r0.xz, r0.w, r0
    mad r0.xz, r0, c18, r2.xyyw
    add r6.xy, r0.xzzw, c18.x
    texld r8, r4, s1
    texld r9, r6, s1
    mul_sat r0.xz, r3, c20.w
    mul r5.w, r0.z, r0.x
    cmp r5.w, r3.y, r5.w, c22.z
    mul r0.xzw, r5.w, r8.xyyz
    mad r0.xzw, r12.xyyz, r12.w, r0
    add r9.w, r12.w, -c19.z
    add r5.w, r5.w, r9.w
    add r3.xy, -r6, c18.y
    min r4.xy, r3, r6
    mul_sat r3.xy, r4, c20.w
    mul r9.w, r3.y, r3.x
    cmp r9.w, r4.w, r9.w, c22.z
    mad r0.xzw, r9.xyyz, r9.w, r0
    add r5.w, r5.w, r9.w
    mul r3.xyz, r5.y, c5.xyww
    mad r3.xyz, r5.x, c4.xyww, r3
    mad r3.xyz, r5.z, c6.xyww, r3
    add r3.xyz, r3, c7.xyww
    rcp r3.w, r3.z
    add r4.xy, r3.z, c22
    cmp r2.z, r4.x, r3.w, c19.w
    mul r3.xy, r2.z, r3
    mad r2.xy, r3, c18.xzzw, r2
    add r2.xy, r2, c18.x
    add r3.xy, -r2, c18.y
    min r4.xz, r3.xyyw, r2.xyyw
    texld r3, r2, s1
    mul_sat r2.xy, r4.xzzw, c20.w
    mul r3.w, r2.y, r2.x
    cmp r3.w, r4.y, r3.w, c22.z
    mad r0.xzw, r3.xyyz, r3.w, r0
    add r2.x, r3.w, r5.w
    rcp r2.y, r2.x
    mov_sat r2.x, r2.x
    mul r0.xzw, r0, r2.y
    mul r0.xzw, r2.x, r0
    mul r0.xzw, r6.w, r0
    add r2.xy, r2.w, c21.zwzw
    mul_sat r2.y, r2.y, c22.w
    mul r0.xzw, r0, r2.y
    cmp r0.xzw, -r7.y, c22.z, r0
    add r0.xzw, r0, r1.xyyz
    mul r1.x, r2.w, r2.w
    mad r1.y, r2.w, -c21.x, c21.y
    mul r1.z, r1.w, r2.w
    mul r1.x, r1.y, r1.x
    mul r1.x, r1.x, c1.w
    mul r1.x, r1.x, c2.x
    mul r2.yzw, r1.z, c23.xxyz
    mad r3.w, r1.z, -c16.x, r0.y
    mad r3.xyz, r0.xzww, r1.x, r2.yzww
    cmp r0, r2.x, r3, c23.zzzw
    mov oC0, r0

// approximately 269 instruction slots used (5 texture, 264 arithmetic)
