//=============================================================================
// ModDeathClips - the death clips in ModDeathAnims' animation set: which hit each one
// answers (Zone), when the body may go limp (Handoff, seconds in) and how long it runs
// (Length). Generated by
// tools/make_psa.py from AdventMod/Anims: don't edit by hand.
//=============================================================================
class ModDeathClips extends Object;

struct DeathClip
{
	var name Clip;
	var string Zone;
	var float Handoff;
	var float Length;
};
var array<DeathClip> Clips;

defaultproperties
{
     Clips(0)=(Clip=ModDie_Buckle,Zone="any",Handoff=0.900,Length=1.633)
     Clips(1)=(Clip=ModDie_back_0,Zone="back",Handoff=1.333,Length=2.700)
     Clips(2)=(Clip=ModDie_back_1,Zone="back",Handoff=0.967,Length=3.067)
     Clips(3)=(Clip=ModDie_back_2,Zone="back",Handoff=1.000,Length=2.767)
     Clips(4)=(Clip=ModDie_blast_0,Zone="blast",Handoff=0.350,Length=2.533)
     Clips(5)=(Clip=ModDie_blast_1,Zone="blast",Handoff=0.567,Length=2.600)
     Clips(6)=(Clip=ModDie_blast_2,Zone="blast",Handoff=1.167,Length=3.433)
     Clips(7)=(Clip=ModDie_chest_0,Zone="chest",Handoff=1.567,Length=3.233)
     Clips(8)=(Clip=ModDie_chest_1,Zone="chest",Handoff=1.200,Length=2.367)
     Clips(9)=(Clip=ModDie_chest_2,Zone="chest",Handoff=0.433,Length=2.233)
     Clips(10)=(Clip=ModDie_gut_0,Zone="gut",Handoff=1.467,Length=3.367)
     Clips(11)=(Clip=ModDie_gut_1,Zone="gut",Handoff=1.000,Length=3.233)
     Clips(12)=(Clip=ModDie_gut_2,Zone="gut",Handoff=0.933,Length=3.200)
     Clips(13)=(Clip=ModDie_head_0,Zone="head",Handoff=0.500,Length=3.500)
     Clips(14)=(Clip=ModDie_head_1,Zone="head",Handoff=0.500,Length=1.200)
     Clips(15)=(Clip=ModDie_head_2,Zone="head",Handoff=0.500,Length=1.767)
     Clips(16)=(Clip=ModDie_knees_0,Zone="knees",Handoff=0.767,Length=4.033)
     Clips(17)=(Clip=ModDie_knees_1,Zone="knees",Handoff=0.667,Length=4.100)
     Clips(18)=(Clip=ModDie_knees_2,Zone="knees",Handoff=0.933,Length=3.667)
     Clips(19)=(Clip=ModDie_legleft_0,Zone="legleft",Handoff=1.033,Length=2.933)
     Clips(20)=(Clip=ModDie_legleft_1,Zone="legleft",Handoff=0.833,Length=3.167)
     Clips(21)=(Clip=ModDie_legleft_2,Zone="legleft",Handoff=0.400,Length=3.300)
     Clips(22)=(Clip=ModDie_legright_0,Zone="legright",Handoff=1.133,Length=3.167)
     Clips(23)=(Clip=ModDie_legright_1,Zone="legright",Handoff=1.033,Length=3.333)
     Clips(24)=(Clip=ModDie_legright_2,Zone="legright",Handoff=0.567,Length=2.400)
     Clips(25)=(Clip=ModDie_shoulderleft_0,Zone="shoulderleft",Handoff=0.350,Length=3.000)
     Clips(26)=(Clip=ModDie_shoulderleft_1,Zone="shoulderleft",Handoff=0.367,Length=2.900)
     Clips(27)=(Clip=ModDie_shoulderleft_2,Zone="shoulderleft",Handoff=1.000,Length=2.967)
     Clips(28)=(Clip=ModDie_shoulderright_0,Zone="shoulderright",Handoff=1.333,Length=3.133)
     Clips(29)=(Clip=ModDie_shoulderright_1,Zone="shoulderright",Handoff=0.933,Length=2.733)
     Clips(30)=(Clip=ModDie_shoulderright_2,Zone="shoulderright",Handoff=0.600,Length=2.433)
}
