//=============================================================================
// ModGibParts - the gib parts: static meshes cut from the game's own character
// meshes (tools/ukx_mesh.py -> .psk -> GibSplit -> .ase), imported into AdventMod.u,
// group Gibs, and their table for ModGore. Generated by tools/gen_gibs.py: don't
// edit by hand.
//   Pivot: the part's centre on the standing character, Z up from the feet, X to
//   the side, Y the mesh's forward. Height: the set's standing height (to scale it
//   to the victim). Skin: the material whose Diffuse the parts wear (slot 0; slot 1
//   is the meat on the cuts).
//=============================================================================
class ModGibParts extends Object;

#exec NEW StaticMesh FILE=Gibs\marine_head.ase NAME=marine_head GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\marine_l_lowerarm.ase NAME=marine_l_lowerarm GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\marine_l_lowerleg.ase NAME=marine_l_lowerleg GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\marine_l_upperarm.ase NAME=marine_l_upperarm GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\marine_l_upperleg.ase NAME=marine_l_upperleg GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\marine_r_lowerarm.ase NAME=marine_r_lowerarm GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\marine_r_lowerleg.ase NAME=marine_r_lowerleg GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\marine_r_upperarm.ase NAME=marine_r_upperarm GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\marine_r_upperleg.ase NAME=marine_r_upperleg GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\marine_torso_lower.ase NAME=marine_torso_lower GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\marine_torso_upper.ase NAME=marine_torso_upper GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\seekerinfantry_head.ase NAME=seekerinfantry_head GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\seekerinfantry_l_front_lower.ase NAME=seekerinfantry_l_front_lower GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\seekerinfantry_l_front_upper.ase NAME=seekerinfantry_l_front_upper GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\seekerinfantry_l_lowerarm.ase NAME=seekerinfantry_l_lowerarm GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\seekerinfantry_l_lowerleg.ase NAME=seekerinfantry_l_lowerleg GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\seekerinfantry_l_upperarm.ase NAME=seekerinfantry_l_upperarm GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\seekerinfantry_l_upperleg.ase NAME=seekerinfantry_l_upperleg GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\seekerinfantry_r_front_lower.ase NAME=seekerinfantry_r_front_lower GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\seekerinfantry_r_front_upper.ase NAME=seekerinfantry_r_front_upper GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\seekerinfantry_r_lowerarm.ase NAME=seekerinfantry_r_lowerarm GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\seekerinfantry_r_lowerleg.ase NAME=seekerinfantry_r_lowerleg GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\seekerinfantry_r_upperarm.ase NAME=seekerinfantry_r_upperarm GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\seekerinfantry_r_upperleg.ase NAME=seekerinfantry_r_upperleg GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\seekerinfantry_torso_lower.ase NAME=seekerinfantry_torso_lower GROUP=Gibs
#exec NEW StaticMesh FILE=Gibs\seekerinfantry_torso_upper.ase NAME=seekerinfantry_torso_upper GROUP=Gibs

struct GibPart
{
	var name Set;
	var StaticMesh Mesh;
	var vector Pivot, Size;
	var float Mass;
};

struct GibSet
{
	var name Name;
	var string Skin;
	var float Height;
};

var array<GibPart> Parts;
var array<GibSet> Sets;

defaultproperties
{
     Parts(0)=(Set=marine,Mesh=StaticMesh'AdventMod.Gibs.marine_head',Pivot=(X=-0.38,Y=6.65,Z=151.10),Size=(X=16.54,Y=20.00,Z=20.10),Mass=5.46)
     Parts(1)=(Set=marine,Mesh=StaticMesh'AdventMod.Gibs.marine_l_lowerarm',Pivot=(X=63.09,Y=-1.42,Z=137.11),Size=(X=46.18,Y=13.14,Z=11.20),Mass=1.93)
     Parts(2)=(Set=marine,Mesh=StaticMesh'AdventMod.Gibs.marine_l_lowerleg',Pivot=(X=13.35,Y=4.14,Z=18.30),Size=(X=17.23,Y=30.96,Z=59.09),Mass=14.74)
     Parts(3)=(Set=marine,Mesh=StaticMesh'AdventMod.Gibs.marine_l_upperarm',Pivot=(X=26.77,Y=-2.90,Z=137.75),Size=(X=28.15,Y=13.87,Z=17.41),Mass=2.42)
     Parts(4)=(Set=marine,Mesh=StaticMesh'AdventMod.Gibs.marine_l_upperleg',Pivot=(X=10.66,Y=1.67,Z=80.30),Size=(X=25.32,Y=19.48,Z=48.54),Mass=11.11)
     Parts(5)=(Set=marine,Mesh=StaticMesh'AdventMod.Gibs.marine_r_lowerarm',Pivot=(X=-63.09,Y=-1.42,Z=137.11),Size=(X=46.18,Y=13.14,Z=11.20),Mass=1.93)
     Parts(6)=(Set=marine,Mesh=StaticMesh'AdventMod.Gibs.marine_r_lowerleg',Pivot=(X=-13.37,Y=4.21,Z=17.77),Size=(X=17.23,Y=30.96,Z=58.69),Mass=14.74)
     Parts(7)=(Set=marine,Mesh=StaticMesh'AdventMod.Gibs.marine_r_upperarm',Pivot=(X=-26.82,Y=-2.90,Z=137.80),Size=(X=27.95,Y=13.87,Z=16.10),Mass=2.45)
     Parts(8)=(Set=marine,Mesh=StaticMesh'AdventMod.Gibs.marine_r_upperleg',Pivot=(X=-11.91,Y=1.91,Z=76.31),Size=(X=22.61,Y=18.49,Z=50.71),Mass=10.85)
     Parts(9)=(Set=marine,Mesh=StaticMesh'AdventMod.Gibs.marine_torso_lower',Pivot=(X=0.69,Y=3.27,Z=107.57),Size=(X=27.56,Y=21.68,Z=35.80),Mass=14.26)
     Parts(10)=(Set=marine,Mesh=StaticMesh'AdventMod.Gibs.marine_torso_upper',Pivot=(X=0.18,Y=-0.68,Z=134.63),Size=(X=41.24,Y=25.08,Z=30.89),Mass=18.55)
     Parts(11)=(Set=seekerinfantry,Mesh=StaticMesh'AdventMod.Gibs.seekerinfantry_head',Pivot=(X=-2.71,Y=22.77,Z=191.15),Size=(X=21.09,Y=37.13,Z=27.16),Mass=10.05)
     Parts(12)=(Set=seekerinfantry,Mesh=StaticMesh'AdventMod.Gibs.seekerinfantry_l_front_lower',Pivot=(X=42.62,Y=72.65,Z=30.84),Size=(X=53.43,Y=61.90,Z=73.33),Mass=20.11)
     Parts(13)=(Set=seekerinfantry,Mesh=StaticMesh'AdventMod.Gibs.seekerinfantry_l_front_upper',Pivot=(X=21.88,Y=34.95,Z=86.08),Size=(X=36.55,Y=56.43,Z=56.27),Mass=15.15)
     Parts(14)=(Set=seekerinfantry,Mesh=StaticMesh'AdventMod.Gibs.seekerinfantry_l_lowerarm',Pivot=(X=106.98,Y=-15.31,Z=172.16),Size=(X=94.13,Y=51.06,Z=27.77),Mass=45.30)
     Parts(15)=(Set=seekerinfantry,Mesh=StaticMesh'AdventMod.Gibs.seekerinfantry_l_lowerleg',Pivot=(X=32.18,Y=-67.55,Z=30.72),Size=(X=39.74,Y=80.54,Z=58.00),Mass=37.01)
     Parts(16)=(Set=seekerinfantry,Mesh=StaticMesh'AdventMod.Gibs.seekerinfantry_l_upperarm',Pivot=(X=34.66,Y=-12.43,Z=177.88),Size=(X=78.35,Y=44.32,Z=57.28),Mass=61.82)
     Parts(17)=(Set=seekerinfantry,Mesh=StaticMesh'AdventMod.Gibs.seekerinfantry_l_upperleg',Pivot=(X=16.29,Y=-13.68,Z=58.31),Size=(X=34.10,Y=56.98,Z=70.88),Mass=41.10)
     Parts(18)=(Set=seekerinfantry,Mesh=StaticMesh'AdventMod.Gibs.seekerinfantry_r_front_lower',Pivot=(X=-42.67,Y=73.48,Z=22.16),Size=(X=53.43,Y=61.90,Z=72.33),Mass=18.88)
     Parts(19)=(Set=seekerinfantry,Mesh=StaticMesh'AdventMod.Gibs.seekerinfantry_r_front_upper',Pivot=(X=-21.31,Y=34.97,Z=79.43),Size=(X=39.68,Y=57.54,Z=57.56),Mass=16.25)
     Parts(20)=(Set=seekerinfantry,Mesh=StaticMesh'AdventMod.Gibs.seekerinfantry_r_lowerarm',Pivot=(X=-121.11,Y=-15.50,Z=169.12),Size=(X=92.35,Y=36.29,Z=20.03),Mass=16.62)
     Parts(21)=(Set=seekerinfantry,Mesh=StaticMesh'AdventMod.Gibs.seekerinfantry_r_lowerleg',Pivot=(X=-32.19,Y=-67.55,Z=30.72),Size=(X=39.74,Y=80.54,Z=58.00),Mass=37.01)
     Parts(22)=(Set=seekerinfantry,Mesh=StaticMesh'AdventMod.Gibs.seekerinfantry_r_upperarm',Pivot=(X=-50.59,Y=-13.83,Z=171.16),Size=(X=52.25,Y=28.47,Z=19.99),Mass=12.38)
     Parts(23)=(Set=seekerinfantry,Mesh=StaticMesh'AdventMod.Gibs.seekerinfantry_r_upperleg',Pivot=(X=-15.18,Y=-12.80,Z=58.81),Size=(X=38.93,Y=56.94,Z=70.60),Mass=41.62)
     Parts(24)=(Set=seekerinfantry,Mesh=StaticMesh'AdventMod.Gibs.seekerinfantry_torso_lower',Pivot=(X=-1.35,Y=12.45,Z=112.81),Size=(X=55.86,Y=58.38,Z=94.80),Mass=98.37)
     Parts(25)=(Set=seekerinfantry,Mesh=StaticMesh'AdventMod.Gibs.seekerinfantry_torso_upper',Pivot=(X=-3.41,Y=-2.67,Z=175.11),Size=(X=68.27,Y=52.94,Z=67.92),Mass=124.51)
     Sets(0)=(Name=marine,Skin="humancharacters_tx.secondary.marine_hsh",Height=161.2)
     Sets(1)=(Name=seekerinfantry,Skin="seekercharacters_tx.Main.infantry_hsh",Height=209.1)
}
