//=============================================================================
// ModJiggleBones - the Seeker infantry's jiggle bones (JIGGLE.md): parent, lever (the region's
// centre in the parent's frame), the live spring per bone (k, d, gain, max amplitude) and, for
// the record, the raw fit to the soft-body reference. Generated by tools/make_jiggle_uc.py from
// the fit's JSON: don't edit by hand. ModJiggle sends them to the DLL (JiggleBone lines).
//=============================================================================
class ModJiggleBones extends Object;

var string Names[16];
var string Parents[16];
var vector Lever[16];
var float K[16];
var float D[16];
var float Gain[16];
var float MaxDeg[16];
var float FitK[16];
var float FitD[16];
var float FitGain[16];
var int Count;

defaultproperties
{
     Names(0)="J_Belly"
     Parents(0)="spine1"
     Lever(0)=(X=-1.107,Y=-6.779,Z=19.777)
     K(0)=483.611
     D(0)=13.195
     Gain(0)=0.2464
     MaxDeg(0)=22.30
     FitK(0)=44.753
     FitD(0)=0.480
     FitGain(0)=0.0033
     Names(1)="J_Chest"
     Parents(1)="spine2"
     Lever(1)=(X=0.144,Y=-4.727,Z=18.372)
     K(1)=483.611
     D(1)=13.195
     Gain(1)=0.2633
     MaxDeg(1)=30.00
     FitK(1)=115.501
     FitD(1)=166.372
     FitGain(1)=0.1374
     Names(2)="J_Hump"
     Parents(2)="spine2"
     Lever(2)=(X=-4.482,Y=1.098,Z=-12.626)
     K(2)=483.611
     D(2)=13.195
     Gain(2)=0.1601
     MaxDeg(2)=20.62
     FitK(2)=593.881
     FitD(2)=7.207
     FitGain(2)=0.0000
     Names(3)="J_Throat"
     Parents(3)="Neck02"
     Lever(3)=(X=0.206,Y=3.009,Z=8.868)
     K(3)=483.611
     D(3)=13.195
     Gain(3)=0.1445
     MaxDeg(3)=30.00
     FitK(3)=27.154
     FitD(3)=0.000
     FitGain(3)=0.0023
     Names(4)="J_ArmR"
     Parents(4)="rightArm"
     Lever(4)=(X=-25.312,Y=3.443,Z=2.447)
     K(4)=483.611
     D(4)=13.195
     Gain(4)=0.3512
     MaxDeg(4)=22.19
     FitK(4)=2794.321
     FitD(4)=9.396
     FitGain(4)=0.2729
     Names(5)="J_ArmL"
     Parents(5)="leftArm"
     Lever(5)=(X=14.738,Y=-3.312,Z=3.451)
     K(5)=483.611
     D(5)=13.195
     Gain(5)=0.2250
     MaxDeg(5)=22.69
     FitK(5)=1158.386
     FitD(5)=18.124
     FitGain(5)=0.1305
     Names(6)="J_FrontArmR"
     Parents(6)="RightFrontArm"
     Lever(6)=(X=-6.925,Y=0.927,Z=20.108)
     K(6)=483.611
     D(6)=13.195
     Gain(6)=0.2007
     MaxDeg(6)=14.00
     FitK(6)=343.406
     FitD(6)=163.683
     FitGain(6)=0.0728
     Names(7)="J_FrontArmL"
     Parents(7)="LeftFrontArm"
     Lever(7)=(X=5.710,Y=1.206,Z=17.272)
     K(7)=483.611
     D(7)=13.195
     Gain(7)=0.2579
     MaxDeg(7)=18.70
     FitK(7)=1.824
     FitD(7)=3.172
     FitGain(7)=0.0000
     Names(8)="J_ThighR"
     Parents(8)="rightUpLeg"
     Lever(8)=(X=-1.781,Y=26.931,Z=-5.813)
     K(8)=483.611
     D(8)=13.195
     Gain(8)=0.3317
     MaxDeg(8)=17.94
     FitK(8)=1339.856
     FitD(8)=2.627
     FitGain(8)=0.0000
     Names(9)="J_ThighL"
     Parents(9)="leftUpLeg"
     Lever(9)=(X=3.018,Y=28.178,Z=-6.620)
     K(9)=483.611
     D(9)=13.195
     Gain(9)=0.3191
     MaxDeg(9)=15.59
     FitK(9)=52.727
     FitD(9)=0.000
     FitGain(9)=0.0000
     Count=10
}
