//=============================================================================
// ModRagdollBones - the ragdoll skeletons in KarmaData\Advent.ka and the bones each
// needs (Bones[First .. First+Count-1]), for ModGore.Limp. Generated by
// tools/make_ka.py: don't edit by hand.
//=============================================================================
class ModRagdollBones extends Object;

struct Skeleton
{
	var string Name;
	var int First, Count;
};
var array<Skeleton> Skeletons;
var array<name> Bones;

defaultproperties
{
     Skeletons(0)=(Name="humanMale2",First=0,Count=12)
     Skeletons(1)=(Name="seeker",First=12,Count=18)
     Skeletons(2)=(Name="seekerhound",First=30,Count=14)
     Bones(0)=hips
     Bones(1)=spine1
     Bones(2)=Spine3
     Bones(3)=head
     Bones(4)=leftArm
     Bones(5)=leftForeArm
     Bones(6)=rightArm
     Bones(7)=rightForeArm
     Bones(8)=leftUpLeg
     Bones(9)=leftLeg
     Bones(10)=rightUpLeg
     Bones(11)=rightLeg
     Bones(12)=hips
     Bones(13)=spine1
     Bones(14)=spine2
     Bones(15)=head
     Bones(16)=leftArm
     Bones(17)=leftForeArm
     Bones(18)=rightArm
     Bones(19)=rightForeArm
     Bones(20)=LeftFrontArm
     Bones(21)=LeftFrontElbow
     Bones(22)=RightFrontArm
     Bones(23)=RightFrontElbow
     Bones(24)=leftUpLeg
     Bones(25)=leftLeg
     Bones(26)=leftFoot
     Bones(27)=rightUpLeg
     Bones(28)=rightLeg
     Bones(29)=rightFoot
     Bones(30)=hips
     Bones(31)=spine1
     Bones(32)=spine2
     Bones(33)=head
     Bones(34)=LeftFrontArm
     Bones(35)=LeftFrontElbow
     Bones(36)=RightFrontArm
     Bones(37)=RightFrontElbow
     Bones(38)=leftUpLeg
     Bones(39)=leftLeg
     Bones(40)=leftFoot
     Bones(41)=rightUpLeg
     Bones(42)=rightLeg
     Bones(43)=rightFoot
}
