//=============================================================================
// ModSkins - the skin materials each character mesh wears by default, slot by slot (full
// object paths, loaded when needed). Generated by tools/gen_skins.py: don't edit by hand.
//=============================================================================
class ModSkins extends Object;

struct MeshSkins
{
	var string Mesh;       // the mesh's name, in capitals
	var string Skin[4];
};
var array<MeshSkins> Meshes;

// the entry for a mesh (-1 none)
static function int Find(Mesh M)
{
	local string N;
	local int i;

	if (M == None)
		return -1;
	N = Caps(string(M.Name));
	for (i = 0; i < default.Meshes.Length; i++)
		if (default.Meshes[i].Mesh == N)
			return i;
	return -1;
}

defaultproperties
{
     Meshes(0)=(Mesh="BOUNTYHUNTER1",Skin[0]="extracharacters_tx.bountyHunters.bh1_hsh")
     Meshes(1)=(Mesh="BOUNTYHUNTER2",Skin[0]="extracharacters_tx.bountyHunters.bh2_hsh")
     Meshes(2)=(Mesh="BOUNTYHUNTER3",Skin[0]="extracharacters_tx.bountyHunters.BH3_HSH")
     Meshes(3)=(Mesh="SEEKERCOMMANDER",Skin[0]="seekercharacters_tx.Main.comanderu_hsh")
     Meshes(4)=(Mesh="SEEKERELITE",Skin[0]="seekercharacters_tx.Main.eliteu_hsh")
     Meshes(5)=(Mesh="SEEKERSCANNER",Skin[0]="seekercharacters_tx.Main.seekerscanner_hsh")
     Meshes(6)=(Mesh="ADMIRALTORN",Skin[0]="humancharacters_tx.secondary.Admiral_HSH",Skin[1]="humancharacters_tx.secondary.AdmiralFace_HSH")
     Meshes(7)=(Mesh="AURELIANMALE",Skin[0]="aureliancharacters_tx.secondary.GenericMale_HSH")
     Meshes(8)=(Mesh="AURELIANSEN01",Skin[0]="aureliancharacters_tx.secondary.Senator_HSH",Skin[1]="aureliancharacters_tx.secondary.elrobe_hsh")
     Meshes(9)=(Mesh="BOUNTYHUNTER2_SHIP",Skin[0]="extracharacters_tx.bountyHunters.bh2ship_hsh")
     Meshes(10)=(Mesh="BUD",Skin[0]="humancharacters_tx.secondary.marine_nohelmet_hsh",Skin[1]="humancharacters_tx.secondary.facebase_hsh")
     Meshes(11)=(Mesh="ELITEFORMALWARRIOR",Skin[0]="aureliancharacters_tx.secondary.EliteArmor_HSH",Skin[1]="aureliancharacters_tx.secondary.elite_hsh",Skin[2]="aureliancharacters_tx.secondary.elrobe_hsh")
     Meshes(12)=(Mesh="ELITEWARRIOR",Skin[0]="aureliancharacters_tx.secondary.elite_hsh",Skin[1]="aureliancharacters_tx.secondary.EliteArmor_HSH",Skin[2]="aureliancharacters_tx.secondary.fin1_hsh")
     Meshes(13)=(Mesh="ENDSNOWALIEN",Skin[0]="humancharacters_tx.Main.snowguyop_hsh")
     Meshes(14)=(Mesh="ENGINEER",Skin[0]="humancharacters_tx.secondary.digs_hsh",Skin[1]="humancharacters_tx.secondary.facebase_hsh")
     Meshes(15)=(Mesh="ETHANPILOT",Skin[0]="humancharacters_tx.secondary.pilot_hsh",Skin[1]="humancharacters_tx.Main.ethanface_hsh")
     Meshes(16)=(Mesh="ETHANWYETH",Skin[0]="humancharacters_tx.Main.ethanface_hsh",Skin[1]="humancharacters_tx.Main.ethanbody_hsh")
     Meshes(17)=(Mesh="FEMALEAURELIAN",Skin[0]="aureliancharacters_tx.secondary.female_hsh")
     Meshes(18)=(Mesh="FODDER",Skin[0]="extracharacters_tx.bountyHunters.Robosapien_HSH")
     Meshes(19)=(Mesh="GIDEONEND",Skin[0]="humancharacters_tx.Main.gideonend_hsh",Skin[1]="humancharacters_tx.Main.gideonface_endhsh")
     Meshes(20)=(Mesh="GIDEONFORMAL",Skin[0]="humancharacters_tx.Main.gideonface_buzz_hair_hsh",Skin[1]="humancharacters_tx.Main.gideon_hsh")
     Meshes(21)=(Mesh="GIDEONPILOTLONGHAIR",Skin[0]="humancharacters_tx.Main.gideonface_scarhsh",Skin[1]="humancharacters_tx.secondary.pilot_hsh")
     Meshes(22)=(Mesh="GIDEONPNOHELM",Skin[0]="humancharacters_tx.Main.gideonface_buzz_hair_hsh",Skin[1]="humancharacters_tx.secondary.pilot_hsh")
     Meshes(23)=(Mesh="GIDEONWYETH",Skin[0]="humancharacters_tx.Main.gideonface_scarhsh",Skin[1]="humancharacters_tx.Main.gideon_hsh")
     Meshes(24)=(Mesh="GIDEONWYETHSHORTHAIR",Skin[0]="humancharacters_tx.Main.gideon_hsh",Skin[1]="humancharacters_tx.Main.gideonface_buzz_hair_hsh")
     Meshes(25)=(Mesh="HUMANDIPLOMATE",Skin[0]="humancharacters_tx.secondary.Diplomat_HSH",Skin[1]="humancharacters_tx.secondary.DiplomatFace_HSH")
     Meshes(26)=(Mesh="HUMANFEMALE",Skin[0]="humancharacters_tx.secondary.Genericfemale_HSH")
     Meshes(27)=(Mesh="HUMANMALE",Skin[0]="humancharacters_tx.secondary.Male_HSH",Skin[1]="humancharacters_tx.secondary.MaleFace_HSH")
     Meshes(28)=(Mesh="INFANTRY",Skin[0]="seekercharacters_tx.Main.infantry_hsh",Skin[1]="aureliancharacters_tx.secondary.InfantryArmor_HSH",Skin[2]="aureliancharacters_tx.secondary.jetpack_hsh",Skin[3]="aureliancharacters_tx.secondary.badfin_hsh")
     Meshes(29)=(Mesh="KALEHMARMORED",Skin[0]="aureliancharacters_tx.Main.KelehmArmor2_HSH",Skin[1]="aureliancharacters_tx.Main.kelehmarmor_hsh",Skin[2]="aureliancharacters_tx.Main.kelehm_hsh",Skin[3]="aureliancharacters_tx.Main.kelehmrobes_hsh")
     Meshes(30)=(Mesh="KCHELL",Skin[0]="humancharacters_tx.secondary.Ambassador_HSH")
     Meshes(31)=(Mesh="KELEHM",Skin[0]="aureliancharacters_tx.Main.kelehm_hsh",Skin[1]="aureliancharacters_tx.secondary.elrobe_hsh")
     Meshes(32)=(Mesh="KOROEMETHAN",Skin[0]="extracharacters_tx.koroem.KoroemEthanface2_HSH",Skin[1]="extracharacters_tx.koroem.ethanbod01_hsh",Skin[2]="humancharacters_tx.Main.ethanbody_hsh")
     Meshes(33)=(Mesh="KOROEMOLIVIA",Skin[0]="extracharacters_tx.koroem.koroemoliviadress_hsh",Skin[1]="extracharacters_tx.koroem.OliviaFace2_HSH")
     Meshes(34)=(Mesh="LANDWELL",Skin[0]="humancharacters_tx.secondary.Ambassador_HSH")
     Meshes(35)=(Mesh="LURIAMWORKER",Skin[0]="humancharacters_tx.secondary.luriamworker_hsh",Skin[1]="humancharacters_tx.secondary.facebase_hsh")
     Meshes(36)=(Mesh="MARINE",Skin[0]="humancharacters_tx.secondary.marine_hsh")
     Meshes(37)=(Mesh="MARINSPACE",Skin[0]="humancharacters_tx.Main.marinspace_hsh")
     Meshes(38)=(Mesh="MARINSTEEL",Skin[0]="humancharacters_tx.Main.marin_hsh",Skin[1]="humancharacters_tx.Main.marinface_hsh")
     Meshes(39)=(Mesh="MARINSTEELCOAT",Skin[0]="humancharacters_tx.Main.marin_hsh",Skin[1]="humancharacters_tx.Main.marinface_hsh")
     Meshes(40)=(Mesh="MARINSTEELEND",Skin[0]="humancharacters_tx.Main.endmarinface_hsh",Skin[1]="humancharacters_tx.Main.endmarin01_hsh",Skin[2]="humancharacters_tx.Main.Endmarin_HSH")
     Meshes(41)=(Mesh="MECHANIC",Skin[0]="humancharacters_tx.secondary.mechanic_HSH")
     Meshes(42)=(Mesh="OFFICER",Skin[0]="humancharacters_tx.secondary.officer_hsh")
     Meshes(43)=(Mesh="OLIVIAMORGAN",Skin[0]="humancharacters_tx.Main.olivia_hsh",Skin[1]="humancharacters_tx.Main.oliviaface_hsh")
     Meshes(44)=(Mesh="OLIVIAMORGANLABCOAT",Skin[0]="humancharacters_tx.Main.olivia_hsh",Skin[1]="humancharacters_tx.Main.oliviaface_hsh")
     Meshes(45)=(Mesh="OLIVIAMORGANLONGHAIR",Skin[0]="humancharacters_tx.Main.oliviaface_hsh",Skin[1]="humancharacters_tx.Main.OliviaLong_HSH",Skin[2]="humancharacters_tx.Main.OliviaLong_HSH")
     Meshes(46)=(Mesh="OLIVIASPACE",Skin[0]="humancharacters_tx.Main.oliviaspace_hsh")
     Meshes(47)=(Mesh="PILOT",Skin[0]="humancharacters_tx.secondary.pilot_hsh")
     Meshes(48)=(Mesh="SCIENTIST",Skin[0]="humancharacters_tx.secondary.scientist_hsh",Skin[1]="humancharacters_tx.secondary.face_sci_hsh")
     Meshes(49)=(Mesh="SEEKERHOUND",Skin[0]="seekercharacters_tx.Main.seekerhound_hsh")
     Meshes(50)=(Mesh="SEEKERINFANTRY",Skin[0]="seekercharacters_tx.Main.infantry_hsh")
     Meshes(51)=(Mesh="SEEKERPILOT",Skin[0]="seekercharacters_tx.Main.skrspace_hsh")
     Meshes(52)=(Mesh="SEEKERSHOCKTROOPER",Skin[0]="seekercharacters_tx.Main.shocktrooper_hsh")
     Meshes(53)=(Mesh="SEVAN",Skin[0]="aureliancharacters_tx.Main.sevan_hsh",Skin[1]="aureliancharacters_tx.secondary.badrobes_hsh")
     Meshes(54)=(Mesh="SPECOPS",Skin[0]="humancharacters_tx.secondary.specops_hsh")
}
