//=============================================================================
// The baked building cards (toolsake_cards.py over the scripted models,
// toolsuild_buildings.py): 8 views each, frame k = camera at k*45 degrees
// clockwise round the building. AvalonCards finds them by name:
//   Cards[n]="<Name> X Y Yaw Size [Frames] [Lift]"  ->  U2AvalonCards.<Name>0..7
// This class only exists to hold the imports.
//=============================================================================

class CardTextures extends Object;

#exec TEXTURE IMPORT NAME=CoolingTower0 FILE=Textures\CoolingTower0.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CoolingTower1 FILE=Textures\CoolingTower1.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CoolingTower2 FILE=Textures\CoolingTower2.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CoolingTower3 FILE=Textures\CoolingTower3.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CoolingTower4 FILE=Textures\CoolingTower4.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CoolingTower5 FILE=Textures\CoolingTower5.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CoolingTower6 FILE=Textures\CoolingTower6.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CoolingTower7 FILE=Textures\CoolingTower7.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP

#exec TEXTURE IMPORT NAME=ProcessingHall0 FILE=Textures\ProcessingHall0.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=ProcessingHall1 FILE=Textures\ProcessingHall1.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=ProcessingHall2 FILE=Textures\ProcessingHall2.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=ProcessingHall3 FILE=Textures\ProcessingHall3.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=ProcessingHall4 FILE=Textures\ProcessingHall4.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=ProcessingHall5 FILE=Textures\ProcessingHall5.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=ProcessingHall6 FILE=Textures\ProcessingHall6.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=ProcessingHall7 FILE=Textures\ProcessingHall7.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP

#exec TEXTURE IMPORT NAME=StorageTank0 FILE=Textures\StorageTank0.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=StorageTank1 FILE=Textures\StorageTank1.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=StorageTank2 FILE=Textures\StorageTank2.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=StorageTank3 FILE=Textures\StorageTank3.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=StorageTank4 FILE=Textures\StorageTank4.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=StorageTank5 FILE=Textures\StorageTank5.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=StorageTank6 FILE=Textures\StorageTank6.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=StorageTank7 FILE=Textures\StorageTank7.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP

#exec TEXTURE IMPORT NAME=OreTank0 FILE=Textures\OreTank0.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=OreTank1 FILE=Textures\OreTank1.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=OreTank2 FILE=Textures\OreTank2.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=OreTank3 FILE=Textures\OreTank3.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=OreTank4 FILE=Textures\OreTank4.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=OreTank5 FILE=Textures\OreTank5.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=OreTank6 FILE=Textures\OreTank6.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=OreTank7 FILE=Textures\OreTank7.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP

#exec TEXTURE IMPORT NAME=DockCrane0 FILE=Textures\DockCrane0.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DockCrane1 FILE=Textures\DockCrane1.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DockCrane2 FILE=Textures\DockCrane2.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DockCrane3 FILE=Textures\DockCrane3.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DockCrane4 FILE=Textures\DockCrane4.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DockCrane5 FILE=Textures\DockCrane5.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DockCrane6 FILE=Textures\DockCrane6.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DockCrane7 FILE=Textures\DockCrane7.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP

#exec TEXTURE IMPORT NAME=DrillingRig0 FILE=Textures\DrillingRig0.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DrillingRig1 FILE=Textures\DrillingRig1.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DrillingRig2 FILE=Textures\DrillingRig2.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DrillingRig3 FILE=Textures\DrillingRig3.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DrillingRig4 FILE=Textures\DrillingRig4.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DrillingRig5 FILE=Textures\DrillingRig5.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DrillingRig6 FILE=Textures\DrillingRig6.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DrillingRig7 FILE=Textures\DrillingRig7.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP

#exec TEXTURE IMPORT NAME=DeadRig0 FILE=Textures\DeadRig0.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DeadRig1 FILE=Textures\DeadRig1.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DeadRig2 FILE=Textures\DeadRig2.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DeadRig3 FILE=Textures\DeadRig3.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DeadRig4 FILE=Textures\DeadRig4.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DeadRig5 FILE=Textures\DeadRig5.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DeadRig6 FILE=Textures\DeadRig6.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DeadRig7 FILE=Textures\DeadRig7.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP

#exec TEXTURE IMPORT NAME=CargoDropship0 FILE=Textures\CargoDropship0.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CargoDropship1 FILE=Textures\CargoDropship1.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CargoDropship2 FILE=Textures\CargoDropship2.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CargoDropship3 FILE=Textures\CargoDropship3.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CargoDropship4 FILE=Textures\CargoDropship4.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CargoDropship5 FILE=Textures\CargoDropship5.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CargoDropship6 FILE=Textures\CargoDropship6.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CargoDropship7 FILE=Textures\CargoDropship7.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP

#exec TEXTURE IMPORT NAME=Pylon0 FILE=Textures\Pylon0.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=Pylon1 FILE=Textures\Pylon1.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=Pylon2 FILE=Textures\Pylon2.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=Pylon3 FILE=Textures\Pylon3.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=Pylon4 FILE=Textures\Pylon4.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=Pylon5 FILE=Textures\Pylon5.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=Pylon6 FILE=Textures\Pylon6.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=Pylon7 FILE=Textures\Pylon7.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP

#exec TEXTURE IMPORT NAME=RadioMast0 FILE=Textures\RadioMast0.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=RadioMast1 FILE=Textures\RadioMast1.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=RadioMast2 FILE=Textures\RadioMast2.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=RadioMast3 FILE=Textures\RadioMast3.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=RadioMast4 FILE=Textures\RadioMast4.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=RadioMast5 FILE=Textures\RadioMast5.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=RadioMast6 FILE=Textures\RadioMast6.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=RadioMast7 FILE=Textures\RadioMast7.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
