//=============================================================================
// Round-2 concept buildings as 8-view imposter cards (2026-10-07, the user's picks): the Liandri crane
// temple-tower (from the low-sun Kontext paint-over), the blue A-frame hut with its orange roof edge
// and the blue dorm pod with its orange top band (Sana concepts, recoloured), the Tin Row shack.
// Hunyuan models in Documents\U2Golem\round2, baked by tools\bake_cards.py. Placed by AvalonCards
// Extras[] (U2Avalon/tools/motion.py). This class only holds the imports.
//=============================================================================
class Round2Cards extends Object;

#exec TEXTURE IMPORT NAME=CraneTower0 FILE=Textures\CraneTower0.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CraneTower1 FILE=Textures\CraneTower1.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CraneTower2 FILE=Textures\CraneTower2.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CraneTower3 FILE=Textures\CraneTower3.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CraneTower4 FILE=Textures\CraneTower4.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CraneTower5 FILE=Textures\CraneTower5.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CraneTower6 FILE=Textures\CraneTower6.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=CraneTower7 FILE=Textures\CraneTower7.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=AFrameHut0 FILE=Textures\AFrameHut0.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=AFrameHut1 FILE=Textures\AFrameHut1.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=AFrameHut2 FILE=Textures\AFrameHut2.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=AFrameHut3 FILE=Textures\AFrameHut3.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=AFrameHut4 FILE=Textures\AFrameHut4.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=AFrameHut5 FILE=Textures\AFrameHut5.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=AFrameHut6 FILE=Textures\AFrameHut6.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=AFrameHut7 FILE=Textures\AFrameHut7.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DormPod0 FILE=Textures\DormPod0.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DormPod1 FILE=Textures\DormPod1.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DormPod2 FILE=Textures\DormPod2.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DormPod3 FILE=Textures\DormPod3.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DormPod4 FILE=Textures\DormPod4.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DormPod5 FILE=Textures\DormPod5.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DormPod6 FILE=Textures\DormPod6.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=DormPod7 FILE=Textures\DormPod7.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=TinShack0 FILE=Textures\TinShack0.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=TinShack1 FILE=Textures\TinShack1.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=TinShack2 FILE=Textures\TinShack2.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=TinShack3 FILE=Textures\TinShack3.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=TinShack4 FILE=Textures\TinShack4.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=TinShack5 FILE=Textures\TinShack5.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=TinShack6 FILE=Textures\TinShack6.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
#exec TEXTURE IMPORT NAME=TinShack7 FILE=Textures\TinShack7.tga MIPS=On ALPHA=1 UCLAMPMODE=CLAMP VCLAMPMODE=CLAMP
