r"""Pictures of a level from where the player actually goes: eye height, inside the playable area.

    py playshots.py MAP [n=24] [dirs=4] [look=X,Y] [mutator=U2AvalonCards.AvalonCards] [run=1] [refresh=0]

The playable area is the level designers' own: the AI navigation network (PathNodes, PlayerStarts and every
other NavigationPoint) marks the space a pawn is meant to stand in. The points are read once from the map
with UnrealEd (U2EdBridge/uedlib; cached in runs/navpoints_<MAP>.json, refresh=1 re-reads), a spread-out
subset of n is picked (farthest-point sampling from the first PlayerStart), and a pilot run stands the
player on each (hub tp to the point's own location: a NavigationPoint sits at standing-pawn height, so the
camera is the real eye) and shoots `dirs` directions. The first direction faces `look` (default: the
centre of the chosen points) so every set has one shot toward the place being judged.

Output in runs/<stamp>_playshots_<MAP>/: the run's frames, sheet_<k>.png (labelled contact sheets, 4x4),
plan.png (top-down map of the points with their numbers and first-shot arrows), index.json.
"""
import json, math, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
CODES = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
sys.path.insert(0, os.path.join(CODES, "tools", "C", "U2EdBridge"))

a = [x for x in sys.argv[1:] if "=" not in x]
o = dict(x.split("=", 1) for x in sys.argv[1:] if "=" in x)
MAP = a[0] if a else "TutA"
N = int(o.get("n", 24))
DIRS = int(o.get("dirs", 4))
MUT = o.get("mutator", "U2AvalonCards.AvalonCards")
RUN = o.get("run", "1") != "0"
CACHE = os.path.join(HERE, "runs", "navpoints_%s.json" % MAP)


def read_navpoints():
    from uedlib import session

    def job(ed):
        ed.exec("!answer yes")
        ed.load(MAP)
        pts = []
        for x in ed.actors("NavigationPoint", subclasses=True):
            if "Location" in x:
                pts.append({"class": x.get("Class"), "name": x.get("Name"), "loc": list(x["Location"])})
        return pts
    pts = session(job)
    os.makedirs(os.path.dirname(CACHE), exist_ok=True)
    json.dump(pts, open(CACHE, "w"), indent=1)
    return pts


if o.get("refresh", "0") == "1" or not os.path.exists(CACHE):
    print("reading navigation points from", MAP, "with UnrealEd ...", flush=True)
    pts = read_navpoints()
else:
    pts = json.load(open(CACHE))
print(len(pts), "navigation points:", ", ".join(sorted({p["class"] for p in pts})), flush=True)
if not pts:
    raise SystemExit("no navigation points in " + MAP)

# farthest-point sampling, starting at the first PlayerStart (where the level begins)
start = next((p for p in pts if p["class"] == "PlayerStart"), pts[0])
chosen = [start]
d = [math.dist(p["loc"], start["loc"]) for p in pts]
while len(chosen) < min(N, len(pts)):
    k = max(range(len(pts)), key=lambda i: d[i])
    if d[k] < 150:                         # everything left is within 3 m of a chosen point
        break
    chosen.append(pts[k])
    d = [min(d[i], math.dist(pts[i]["loc"], pts[k]["loc"])) for i in range(len(pts))]
if "look" in o:
    LX, LY = (float(v) for v in o["look"].split(","))
else:
    LX = sum(p["loc"][0] for p in chosen) / len(chosen)
    LY = sum(p["loc"][1] for p in chosen) / len(chosen)

lines = ["# playshots of %s: %d points x %d directions, generated by playshots.py" % (MAP, len(chosen), DIRS),
         "background", "map %s%s" % (MAP, "?Mutator=" + MUT if MUT else ""), "waitcontrol 240", "wait 2", "console god"]
index = []
for k, p in enumerate(chosen):
    x, y, z = p["loc"]
    first = math.degrees(math.atan2(LY - y, LX - x))
    lines.append("console hub tp %.0f %.0f %.0f" % (x, y, z))
    for j in range(DIRS):
        yaw = (first + j * 360.0 / DIRS) % 360
        lines += ["console hub face %.0f" % yaw, "wait 0.7", "shot"]
        index.append({"frame": len(index), "point": k, "class": p["class"], "name": p["name"], "loc": p["loc"], "yaw": round(yaw)})
lines.append("quit")
script = os.path.join(HERE, "scripts", "playshots_%s.txt" % MAP.lower())
open(script, "w").write("\n".join(lines) + "\n")
print("script ->", script, "(%d shots)" % len(index), flush=True)
if not RUN:
    raise SystemExit(0)

subprocess.run([sys.executable, os.path.join(HERE, "u2pilot.py"), script, "--background"], cwd=HERE)
runs = sorted(r for r in os.listdir(os.path.join(HERE, "runs")) if r.endswith("_playshots_%s" % MAP.lower()))
run = os.path.join(HERE, "runs", runs[-1])
frames = sorted(f for f in os.listdir(os.path.join(run, "frames")) if f.lower().endswith((".bmp", ".png")))
json.dump(index, open(os.path.join(run, "index.json"), "w"), indent=1)
if len(frames) != len(index):
    print("WARNING: %d frames for %d shots (a teleport may have failed: see Unreal2.log 'Hub: tp')" % (len(frames), len(index)))

from PIL import Image, ImageDraw
# contact sheets, 4x4, labelled "P<point> <yaw>"
W, H = 480, 270
for s in range(0, len(frames), 16):
    sheet = Image.new("RGB", (W * 4, H * 4))
    dr = ImageDraw.Draw(sheet)
    for k, f in enumerate(frames[s:s + 16]):
        im = Image.open(os.path.join(run, "frames", f)).convert("RGB").resize((W, H))
        x0, y0 = (k % 4) * W, (k // 4) * H
        sheet.paste(im, (x0, y0))
        if s + k < len(index):
            e = index[s + k]
            dr.rectangle([x0, y0, x0 + 120, y0 + 18], fill=(0, 0, 0))
            dr.text((x0 + 4, y0 + 3), "P%02d  yaw %d" % (e["point"], e["yaw"]), fill=(255, 255, 0))
    sheet.save(os.path.join(run, "sheet_%d.png" % (s // 16 + 1)))
# plan: all navigation points grey, chosen ones numbered with an arrow to the first shot's direction
xs = [p["loc"][0] for p in pts] + [LX]
ys = [p["loc"][1] for p in pts] + [LY]
x0, x1, y0, y1 = min(xs), max(xs), min(ys), max(ys)
span = max(x1 - x0, y1 - y0, 1.0)
S = 900


def px(x, y):
    return 30 + (x - x0) / span * (S - 60), S - 30 - (y - y0) / span * (S - 60)


plan = Image.new("RGB", (S, S), (24, 28, 34))
dr = ImageDraw.Draw(plan)
for p in pts:
    u, v = px(*p["loc"][:2])
    dr.ellipse([u - 2, v - 2, u + 2, v + 2], fill=(110, 110, 120))
u, v = px(LX, LY)
dr.line([u - 8, v, u + 8, v], fill=(255, 80, 80), width=2)
dr.line([u, v - 8, u, v + 8], fill=(255, 80, 80), width=2)
for k, p in enumerate(chosen):
    u, v = px(*p["loc"][:2])
    a_ = math.atan2(LY - p["loc"][1], LX - p["loc"][0])
    dr.line([u, v, u + 22 * math.cos(a_), v - 22 * math.sin(a_)], fill=(255, 220, 0), width=2)
    dr.ellipse([u - 5, v - 5, u + 5, v + 5], fill=(255, 220, 0))
    dr.text((u + 7, v - 7), "P%02d" % k, fill=(255, 255, 255))
dr.text((10, 8), "%s: %d navigation points (grey), %d shot points, + = look target" % (MAP, len(pts), len(chosen)), fill=(220, 220, 220))
plan.save(os.path.join(run, "plan.png"))
print("sheets, plan.png, index.json ->", run)
